### ISSUE TITLE
Validate state transitions

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#1186]
Currently we don't validate state transitions in the app channel.

We can pull in the `pureEVM` work from the previous `wallet` but now that we don't have the requirement that the validate call be synchronous there may be a simpler option.

**Comment by snario** [comment]
Happy to tackle this. Also on a related note, I made this issue: https://github.com/ethereumjs/ethereumjs-vm/issues/677

**Comment by snario** [comment]
Added in #1857
