### ISSUE TITLE
Ledger-rebalancing with a simple hub

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#1199]
Suppose Alice (A) and the hub (H) have a ledger channel L1 open, with `x` deposited against it.
They may need to rebalance if either of their balances dip too low.

This is a bit more challenging for the initial web3torrent release, since the simple hub does not store any states.

**Comment by andrewgordstewart** [comment]
The hard part about the simple hub is that, without storing states, it has no context to know when a deposit should be made.
Here's a protocol which could work:

## Scenario 1
If L1 gets to outcome
```
[
  { destination: A, amount: a},
  { destination: H, amount: b}
]
```
and `a` is below some threshold.

Then
1. A can propose an update
```
[
  { destination: A, amount: a},
  { destination: H, amount: b},
  { destination: A, amount: b-a},
]
```
H signs and responds.
2.  Then, A deposits `b-a`.
3. Then A can propose an update
```
[
  { destination: A, amount: b},
  { destination: H, amount: b},
]
```

Currently, the simple-hub matches any deposit made by `A`. This would cause the hub to submit an extra, unnecessary deposit in step 2. (It no longer has the state when it notices the deposit.)
So, we might need to change the deposit logic so that it doesn't also deposit `b-a` after step 2. 

## Scenario 2:
If L1 gets to outcome
```
[
  { destination: A, amount: b},
  { destination: H, amount: a}
]
```
and `a` is below some threshold.

Then
1. A can propose an update
```
[
  { destination: A, amount: b},
  { destination: H, amount: a},
  { destination: H, amount: b-a},
]
```
2. Then, H deposits `b - a`.
3. Then A can propose an update
```
[
  { destination: A, amount: b},
  { destination: H, amount: b},
]
```

The simple-hub can detect that it should deposit `b-a` here, since
- it can hold onto the state
- it can query the blockchain
- it can detect that its obligated to deposit `b-a`

**Comment by andrewgordstewart** [comment]
An alternative solution is, for the time being, to force users to close-and-withdraw from the ledger channel if it detects either of those scenarios, and re-open a new, balanced ledger channel.

**Comment by tomclose** [comment]
How hard would it be to upgrade the simple hub to store the latest state in a channel?

**Comment by andrewgordstewart** [comment]
It wouldn't be hard to store it in-memory, which would cover most cases. The main argument, I think, for the simple-hub (not storing states) was to remove the database requirement.
