### ISSUE TITLE
Ethereum enable workflow fails if metamask extension "Site Access" is set to "on click"

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#1240]
If the metamask extension is set to on click for site access the Etheurem enable workfow silently fails and the user gets stuck on a blank wallet dialogue.

![image](https://user-images.githubusercontent.com/1620336/76890856-536e6f80-6845-11ea-905b-d162074e2374.png)

**Comment by tomclose** [comment]
For [reference](https://www.computerworld.com/article/3445158/chrome-security-setting.html)

> On click — meaning the extension is able to see and alter what's in your browser only when you actively click it (and then only for the site that's currently open in that specific tab)

**Comment by snario** [comment]
Have we asked @danfinlay what the best course of action might be for us in this case? Seems like we are kind of blocked if the user has it set to On Click and don't know what to do.
