### ISSUE TITLE
Set up some standard actions for all workflows

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#1349]
_Originally posted by @andrewgordstewart in https://github.com/statechannels/monorepo/pull/1333_

**Comment by snario** [comment]
@tomclose  @andrewgordstewart any specific examples of standard actions we could write now?

**Comment by andrewgordstewart** [comment]
https://github.com/statechannels/monorepo/pull/1333/files#diff-af9d021eea475841e669f823043ab0ffL92-L97

I think those are what instigated this issue
