### ISSUE TITLE
Backend interface should not expose internal storage types

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#1529]
The current `Backend` API is exposing the way that data happens to be stored in our current backends. I would expect `privateKeys` to return something like `Array<{privateKey: string, signingAddress: string}>`, like an ORM would do.

_Originally posted by @lalexgap in https://github.com/statechannels/monorepo/pull/1523_

**Comment by snario** [comment]
Curious if we feel there has been an improvement here / if this still warrants an issue

**Comment by andrewgordstewart** [comment]
> Curious if we feel there has been an improvement here / if this still warrants an issue

IMO: no and yes
