### ISSUE TITLE
Split hub-depositing UI into (a) depositing and (b) waiting for mining

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#1600]

**Comment by lalexgap** [comment]
I think this would require the `hub` sending the transactionId of the deposit transaction to the `xstate-wallet`.

**Comment by snario** [comment]
> I think this would require the `hub` sending the transactionId of the deposit transaction to the `xstate-wallet`.

The wallet could also monitor the chain and identify a transaction based on the `channelId`

**Comment by lalexgap** [comment]
> > I think this would require the `hub` sending the transactionId of the deposit transaction to the `xstate-wallet`.
> 
> The wallet could also monitor the chain and identify a transaction based on the `channelId`

Currently since we're not waiting for a transaction to be `x` blocks deep, waiting for the transaction to be published to the chain is the same as waiting for the event to occur, I believe?

If our strategy around chain re-orgs is to just wait until a certain amount of blocks, then this probably makes sense once we're doing that.

**Comment by snario** [comment]
I think we should add `transaction` to the wire protocol like @tomclose suggested
