### ISSUE TITLE
Idempotent `conclude-channel` workflow

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#1601]
Long-term goal: my wallet can call `conclude-channel` at any time, and my wallet will retrieve my funds in bounded time (depending on `CHALLENGE_DURATION`.

For the moment, let's make the simplifying assumption that peer-peer communication always works. This removes the requirement that `conclude-channel` launches challenges to finalize the target channel.

TODO:
- [ ] [Directly funded channels](https://github.com/statechannels/monorepo/issues/1602)
- [ ] [virtual-defunding workflow is idempotent](https://github.com/statechannels/monorepo/issues/1603)

**Comment by snario** [comment]
This can be closed right @andrewgordstewart?

**Comment by andrewgordstewart** [comment]
I don't think so -- we have partially complete tests for idempotency, but the workflow is not actually idempotent yet!
