### ISSUE TITLE
Idempotent conclude-channel workflow in directly funded channels.

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#1602]
State:
- Alice and Bob have a directly-funded channel
- Alice & Bob both start `conclude-channel`
- Bob's wallet is always online
- Alice's wallet "crashes" and restarts

Goal:
- Alice restarts a `conclude-channel` workflow
- The channel is concluded
- Alice can withdraw her money

**Comment by andrewgordstewart** [comment]
>Alice's wallet "crashes" and restarts

We could model this on a test by calling `service.stop()` after certain transitions, and creating a new workflow.

**Comment by junjizhi** [comment]
I found it tricky to simulate the `Alice wallet crashes` case. From my understanding, if we look at what side effects the machine can have, the following events happen in order:

1. machine starts
2. withdraw and return success
3. update store entry (finalized and turnNum, etc.)

Crashing before 2) is fine. Starting conclude-channel workflow again is just like starting from brand new state.

Crashing before 3) is more interesting, because we end up in a state where we have withdrawn and store entries are not updated. Essentially, when implementing `withdraw`,  we want to treat funds already withdrawn as a success case. 

What do you think? @andrewgordstewart @snario 

In my current PR, I only added tests to cover Allice crashing *after* updating store entries and blockchain

**Comment by andrewgordstewart** [comment]
Doesn't these events happen in order (assuming direct funding)?
1. machine starts
2. store entry is updated (turnNum, finalized)
3. "withdraw" (which is currently a noop, so there's limited room for you to test this)
4. success

One issue is that 2 is not an atomic change -- _both_ participants need to sign the final state before moving onto 3.

There's the `supportState` workflow, which could fail after having three types of side effects:
1. I sign the final state, you didn't
2. You sign the final state, I didn't
3. We both sign the final state
(the 4th option, neither of us sign the final state, is just failing before it had any side effects)

I don't yet know a good way to programmatically recreate all three possibilities.

>I found it tricky to simulate the Alice wallet crashes case. 

It could be something like this?
```
alicesService.onTransition(state => {
  if (!crashed && state.value === 'withdrawing'){
    // Alice's wallet "crashed"
    crashed = true;
    alicesService.stop();
    alicesService = interpret(...);
  }
});

Once the service stopped, you can restart it with the same context.

**Comment by junjizhi** [comment]
@andrewgordstewart I may get the events order wrong.

> 2. store entry is updated (turnNum, finalized)
> 3. "withdraw" (which is currently a noop, so there's limited room for you to test this)

This seems troubling to me. Should 3 also be in the atomic transaction together with 2?

If Alice crashes before 3 starts, next time Alice would have to check if withdraw was successful. I'm talking about the future when withdraw is not a noop any more. Alice can't rely on store entries to decide the results of last conclude workflow. Right?

> There's the supportState workflow, which could fail after having three types of side effects:

I'm still fuzzy about the code about this part and will continue looking.

**Comment by andrewgordstewart** [comment]
> If Alice crashes before 3 starts, next time Alice would have to check if withdraw was successful. I'm talking about the future when withdraw is not a noop any more. Alice can't rely on store entries alone to decide the results of last conclude workflow. Right?

Alice can distinguish the three following cases (about the _states_ in the store)
1. The target channel is in the "running" state (it has no states marked `final`)
2. The target channel is in the "closing" state (it has a supported `final` state, but it's not a "conclusion proof")
3. The target channel is in the "closed" state (it has a state marked `final`, supported by everyone)

In case 1, the conclude workflow needs to construct a final state (with the same outcome) and get it supported by everyone.

In case 2, the conclude workflow needs to make sure that the final state has the same outcome (It is possible for you to send me a final state where you take all my money. My wallet should not support that state.)

In case 3, the channel is already concluded, so the conclude workflow just has to _defund_ the channel.

Finally, in the case where the channel is _directly_ funded, Alice can check how much funds are still against the channel to see if it needs to withdraw.

**Comment by junjizhi** [comment]
In the PR, I added the test to cover A crashing before withdrawing.

> Alice can distinguish the three following cases (about the states in the store)
> 1. The target channel is in the "running" state (it has no states marked final)
> 2. The target channel is in the "closing" state (it has a supported final state, but it's not a "conclusion proof")
> 3. The target channel is in the "closed" state (it has a state marked final, supported by everyone)

Case 1 is the same as rerunning the conclude workflow. So it is covered in the test.

About Case 2 and Case 3, I felt that to setup such tests is very involved in the supportState implementation. Basically we are testing the supportState workflow idempotency.

@andrewgordstewart
