### ISSUE TITLE
Other participants are not notified when a user resigns on not their turn

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#1806]
Currently if a user decides to resign on not their turn they just wait for a final state. However no communication is sent to the other participant's wallets. This means that resigning on not your turn will just wait for a final state that's probably not coming.

I think ideally the `wallet` should send a message to other participants indicating they want to close. Perhaps an `Objective`?

**Comment by andrewgordstewart** [comment]
Just to clarify, the wallet currently sends a blockchain challenge after 30 seconds (not tested). So things shouldn't stall out indefinitely
