### ISSUE TITLE
Stuck waiting for deposit when transaction was dropped

### ISSUE THREAD

**Issue by tomclose** [statechannels/statechannels#1905]
Would have expected this transaction to fail, but it didn't. 

![Screen Shot 2020-05-19 at 5 36 14 PM](https://user-images.githubusercontent.com/29596/82353449-61806e00-99f7-11ea-90bd-3f91c4ab7554.png)

[web3torrent.Tue, 19 May 2020 16_36_25 GMT.9c8ee35fd.0x3611aE4BF52DC90324834e7610D6fdb9E3cD6A22.pino.log](https://github.com/statechannels/monorepo/files/4651873/web3torrent.Tue.19.May.2020.16_36_25.GMT.9c8ee35fd.0x3611aE4BF52DC90324834e7610D6fdb9E3cD6A22.pino.log)

**Comment by geoknee** [comment]
https://github.com/MetaMask/metamask-extension/issues/6963 looks like it could be related to nonces
