### ISSUE TITLE
updates to `ChannelClient.updateChannel`

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#1909]
Here is a specific , draft proposal for the `updateChannel` call:

## updateChannel

```
updateChannel(
  channelId: string,
  allocations: TokenAllocations,
  appData: string
): Promise<ChannelResult>
```

**Rejects**:

- [x] (R1) with `"Channel not found"`
  - if wallet has no states for `channelId`
- [ ] (R2) with `"Invalid app data"`
  - if the app data field cannot be decoded according to the channel contracts
- [x] (R3) with `"Not my turn"`
  - if it is not my turn, according to the latest supported state stored by the wallet
- [ ] (R4) with `"Invalid transition"`
  - if the allocations and appData represent an invalid transition according to the channel contract
- [ ] (R5) with `"No response"`
  - if the wallet does not respond
- [x] (R6) with `"Wallet error"`
   - If the wallet threw some other error

**Resolves**:

- with a `ChannelResult`
  - when the wallet notifies the client that it has signed a new, supported state with the given `allocations` and `appData`

**Note**:
- It is possible that the wallet sends a `ChannelUpdated` notification of a new, supported state with the given `allocations` and `appData`, but it is not in response to the call to `updateChannel`.
  In particular, a peer in the channel may have coincidentally made the same update.
  This will not cause the promise returned by `updateChannel` to resolve.
  Instead, it will likely reject with `'Not my turn"`.

_Originally posted by @andrewgordstewart in https://github.com/statechannels/monorepo/issues/1853#issuecomment-630883292_

**Comment by andrewgordstewart** [comment]
I am not sure what's expected around R5. Should the channel client (or provider) reject after a fixed number of attempts, where each attempt fails after a fixed timeout?

That seems roughly what happens, but I think that the promise returned by `updateChannel` is not rejected, and instead simply never resolves.

**Comment by andrewgordstewart** [comment]
Also, should there be an error `"Update in progress"` if the wallet is currently applying an update?

**Comment by lalexgap** [comment]
> I am not sure what's expected around R5. Should the channel client (or provider) reject after a fixed number of attempts, where each attempt fails after a fixed timeout?
> 
> That seems roughly what happens, but I think that the promise returned by `updateChannel` is not rejected, and instead simply never resolves.

We originally had retry logic in the `channel-provider` but I think we ran into some issues around handling duplicate requests. However that may no longer be an issue?

My preference would be to keep it simple and just have a simple timeout. If the timeout expires the promise rejects with the appropriate error for now.

**Comment by lalexgap** [comment]
> Also, should there be an error `"Update in progress"` if the wallet is currently applying an update?

If these calls are being wrapped by transactions I think it's enough to have the second call block until the first one is done and then reject with the appropriate error (or succeed if valid). I don't think the updates are long running enough to be worth adding an "Update in progress" error.

**Comment by andrewgordstewart** [comment]
> My preference would be to keep it simple and just have a simple timeout. If the timeout expires the promise rejects with the appropriate error for now.

With this solution, it would be on the application to retry after the timeout. I'd be ok with this if things are reliably getting results on the [first retry](https://github.com/statechannels/monorepo/blob/master/packages/channel-provider/src/messaging-service.ts#L36).

Based on memory, this doesn't happen. So, we should figure out
- is my memory correct? do `send` methods often fail to get responses within the timeout period
- if yes, why? what should be done about it?

**Comment by lalexgap** [comment]
Right now we're using 0 retries/ infinite timeout in the channel provider I believe: https://github.com/statechannels/monorepo/blob/7aff965e0d9dafa4a20f7df98c4eadbbdd34f58a/packages/channel-provider/src/messaging-service.ts#L17

**Comment by andrewgordstewart** [comment]
So it turns out there are more cases than just "Not my turn" when the wallet should not update the channel. In particular:
- the channel is closing
- the channel is not yet funded

**Comment by andrewgordstewart** [comment]
> Right now we're using 0 retries/ infinite timeout in the channel provider I believe:

<img width="713" alt="Screen Shot 2020-05-21 at 9 21 00 AM" src="https://user-images.githubusercontent.com/8432675/82580788-82a2a500-9b44-11ea-8118-06f503a67c4c.png">

**Comment by andrewgordstewart** [comment]
Added

> (R6) with "Wallet error"
> If the wallet threw some other error

**Comment by andrewgordstewart** [comment]
https://github.com/statechannels/monorepo/blob/7f3a95b0db574f3d0f1979dc8de3cbc4e80fc094/packages/xstate-wallet/src/workflows/application.ts#L351

This TODO is for R2, R4 & R5

**Comment by lalexgap** [comment]
> > Right now we're using 0 retries/ infinite timeout in the channel provider I believe:
> 
> <img alt="Screen Shot 2020-05-21 at 9 21 00 AM" width="713" src="https://user-images.githubusercontent.com/8432675/82580788-82a2a500-9b44-11ea-8118-06f503a67c4c.png">

Hmm, I wonder how this is happening?

**Comment by snario** [comment]
I remember looking at this and I _think_ it's misleading, and that this is not a second attempt at some specific API call but rather just a second API call made before the first API call returned, where those two API calls are independent of each other.
