### ISSUE TITLE
[xstate-wallet] fix xstate visualizer

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#1913]
It would be nice to be able to use https://xstate.js.org/viz/ again. At the moment:
1. Navigate to https://xstate.js.org/viz/.
1. Run `HUB_DESTINATION=0x0000 yarn generateConfigs`
1. Copy contents of `monorepo/packages/xstate-wallet/src/workflows/virtual-funding-as-leaf.config.js` into the visualizer.
1. Observer `Cannot read property 'indexOf' of undefined` errors.

**Comment by tomclose** [comment]
When I updated the `approve-budget-and-fund` workflow, I managed to get the xstate visualization displaying in xstate dev tools. This leads for a nicer dev experience, as you can make changes to the workflow and see it reload live. It should be possible to do this with the other workflows too.
