### ISSUE TITLE
Implement Basic Challenging/Responding workflow

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#1960]
Implement challenging so it can be used in web3torrent.

TODO: Determine what challenging features are needed by web3torrent.

**Comment by snario** [comment]
- Web3Torrent UI shows "disconnected" for a channel that has `status` as `running`
- The red dot and text "disconnected" is clickable
- Clicking the "disconnected" text triggers a call to `ChallengeChannel` in the wallet
- The wallet pops up a modal which asks the user to submit a transaction to the chain
- After submitting the transaction a timeout is triggered
- The UI indicates how long this timeout period will take
- The UI is "exitable" (i.e., you can click "close" or "x" and it closes the modal)
- The `status` of the channel is now `challenged`
- The UI on web3torrent shows a yellow dot and text "challenged"
- If the user clicks on "challenged" then the modal pops up again
- After the timeout period ends a `ChannelUpdated` event is emitted and the channel is now in `closed` state
