### ISSUE TITLE
Metamask error on deposit

### ISSUE THREAD

**Issue by tomclose** [statechannels/statechannels#2024]
Occasionally I get the metamask deposit fails with the following error:
```
[ethjs-rpc] rpc error with payload {"id":569616816970,
 "jsonrpc":"2.0","params":["0xf8cd088509502f9000828608949aca3c3eca5fd2d0d8de18d0f079fefdeba837de843b9aca00b864278f2ab881525ed332b435317eb3ddff0ab7b4725f06c88e092c25b5a7f9b318d4033f34000000000000000000000000000000000000000000000000000000003b9aca00000000000000000000000000000000000000000000000000000000003b9aca002aa032e8601a79af69c7570d26517741abfb70071a0608b5f04f646647c989df8f7fa06fc982c453f84eecdfab409d6fd893f85a021d192f01fe0205cfcf39dbb7305a"],"method":"eth_sendRawTransaction"} [object Object]
```

**Comment by tomclose** [comment]
![Screen Shot 2020-05-29 at 5 24 55 PM](https://user-images.githubusercontent.com/29596/83282493-93e95280-a1d1-11ea-8772-274829effedf.png)

**Comment by lalexgap** [comment]
Could this be a transaction nonce issue? I believe both @tomclose @kerzhner were using the same address in metamask when this issue occurred which means the transaction nonces would get out of sync.
