### ISSUE TITLE
Metamask address switching

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#2126]
The behaviors we are thinking about are:
1. A new user arrives to the app with a Metamask account with 0 eth.
1. An existing user arrives back to the app with a Metamask account different from previous visits.

We would like the following behavior:
1. If a new user has zero funds in metamask account, display a warning.
1. If a new user switches to a different metamask account with funds, the app should work. Perhaps the easiest course of action is to reload the page.
1. If an existing user already has a sufficient budget and loads the page with a different Metamask account, the app should either show an error or work (see #2128)

**Comment by snario** [comment]
#3 is more narrowly focused on by #2128, so I think this issue should only track (1) and (2)
