### ISSUE TITLE
Zero byte, zero transaction, disconnected channels during standup

### ISSUE THREAD

**Issue by tomclose** [statechannels/statechannels#2220]
Tom was the seeder. Mike was downloading

Tom's screen:

![Screen Shot 2020-06-17 at 6 51 38 PM](https://user-images.githubusercontent.com/29596/84932089-a9b0b000-b0cb-11ea-9383-e163e81ee07b.png)

Tom's logs: [web3torrent.Wed, 17 Jun 2020 17_37_13 GMT.214eda71f.0x400b464d87F6F6068CC88bc62843386bc025ce84.pino.log](https://github.com/statechannels/monorepo/files/4794290/web3torrent.Wed.17.Jun.2020.17_37_13.GMT.214eda71f.0x400b464d87F6F6068CC88bc62843386bc025ce84.pino.log)

Mike's logs: [web3torrent.Wed, 17 Jun 2020 17_36_48 GMT.214eda71f.0x3D5067A1D68f6A320f340D277Ae7626FC1B92c72.pino.log](https://github.com/statechannels/monorepo/files/4794316/web3torrent.Wed.17.Jun.2020.17_36_48.GMT.214eda71f.0x3D5067A1D68f6A320f340D277Ae7626FC1B92c72.pino.log)

One of the zero byte channels has id `0x381152d0b0a8a9`. In my store, I see state 0, single signed. In Mike's store he sees state 0, double signed.

* Mike requested data from Tom
* Tom created a channel
* Mike joined the channel but didn't send the update state to Tom

It looked like this happened several times very quickly.

**Comment by tomclose** [comment]
Looked at this with Andrew. The channels were created within 100ms of each other. It seems like something like the following is happening:

A bunch of requests come in on a wire for which there's no `seedingChannelId`. They get processed here:
https://github.com/statechannels/monorepo/blob/dac62999e52740f6e3f31356d2c3a52ad54cca2f/packages/web3torrent/src/library/web3torrent-lib.ts#L265-L278

Note that the channel isn't blocked (which would queue further requests) until the channel id is created. This means that we create multiple channels. 

The block peer `STOP` message contains the `channelId`, but the leecher can only store one of these in the channel, and it overwrites, so the last one wins:

https://github.com/statechannels/monorepo/blob/42eb44ee085088251a7425fe918b2a0f6a2ef274/packages/web3torrent/src/library/paid-streaming-extension.ts#L157-L165

When the channel proposed messages arrives, it signs them but can't tell which wire to send the responses back down.

Outstanding question: is this caused by the seeder cancelling, or has this always been a problem? It's possible that multiple requests only arrive once the wire is underway, and the seeder cancelling has somehow removed the channelId suddenly from an active wire?

**Comment by andrewgordstewart** [comment]
6d57876 makes the change that requests are processed serially. This should prevent the litany of payment channels created through the behaviour outlined above.
