### ISSUE TITLE
Use SI Prefixed Units of ETH in UI

### ISSUE THREAD

**Issue by MicahZoltu** [statechannels/statechannels#2252]
**Problem description :confused:**
The UI presents payments in `wei`, which is a poorly named unit that the vast majority of users don't understand.

**Describe the solution you'd like :rocket:**
Use SI prefixed `ether` or `eth` to make it clear to users what they are getting.

**Describe alternatives you've considered**
None, standards and consistency is good.

**Additional context**
The vast majority of the world is familiar with SI prefixes (main exception being people educated in the US).  Anyone familiar with Ethereum is familiar with `ETH` and `ether`.  Very few people know what a `wei` is.  Rather than showing `Mwei` or `megawei`, instead show `peth` or `picoether` or `picoeth`.

While coming up with clever names for things is sometimes fun for the authors, it is almost never useful for communication with a broad audience.  `wei` came from a "fun little thing for the authors of Ethereum to do" but it is not useful for communicating with a broader audience, so I recommend against using it.

**Comment by geoknee** [comment]
@MicahZoltu thanks for bringing this up. At the very least I will add an entry in the web3Torrent [FAQ](https://www.notion.so/web3Torrent-FAQ-9f384d9dbadc4828aa81e14fcc360466) that points to an explainer on wei. 

Your suggestion would be simple to implement.  In my view, however, it's marginal as to whether it makes the app easier to understand to our users. The Gwei unit, for example, is an SI prefix of wei, and should be widely understood by Ethereum users as it is the standard denomination for transaction fees. As for wider audiences, I take your point that ETH might be more understandable. 

It's also the case that at present 1) the cost per byte is set (by us) in a pretty arbitrary way, using the smallest denomination of ETH for 1 byte and 2) the app is only deployed to a test net. If the app moved to main net we would probably have to reconsider pricing altogether, anyway.

**Comment by MicahZoltu** [comment]
> The Gwei unit, for example, is an SI prefix of wei, and **should be widely understood by Ethereum users** as it is the standard denomination for transaction fees.

I don't think this is true, especially as Ethereum continues to gain adoption and moves away from the technical nerd crowd who know what a wei and a satoshi are.  I *suspect* that most people just treat gwei as "the units of the number I need to make go up to get my transaction in faster but will cost more" rather than "a unit of measure of ETH".  (I actually call it nanoeth for this exact reason, though that is out of scope for this issue).
