### ISSUE TITLE
App protocol

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#2312]
This task involves implementing a protocol which takes the next action, given the current "protocol state".

The protocol state should include
- (roughly) the instance of the app channel's `Channel` model.
- the client request (if any)

The protocol should decide
- whether to notify the client about the channel's current state
- whether to update the channel, or sign an existing state in the channel

## In scope (milestone 0)
- updating the channel

## Out of scope (milestone 0)
- blockchain events
- closing the channel

**Comment by kerzhner** [comment]
Let's think through the `updateChannel` flow:
1. Application invokes `updateChannel` of the `WalletInterface`.
1. The store is queried for the latest channel state.
1. The wallet selects which protocol to run. Let's say the `application` protocol is the protocol that will be run.
1. `application` protocol determines whether to update the channel. It's unclear whether the application protocol does anything besides asking the store to update the channel.
1. The store is asked to update the channel. The success or failure of this operation should be somehow coupled with the `updateChannel` call of step 1.
1. If the store update succeeds, the wallet needs to ask the application to send the latest state to all other participants.

**Comment by kerzhner** [comment]
Open questions:
1. Where does the application request data belong? On the `ChannelState` https://github.com/statechannels/statechannels/blob/95175507dceef0822c046980d8826f5f71b1ae5c/packages/server-wallet/src/protocols/state.ts#L10?
1. Is there a context for each request from the application?

**Comment by kerzhner** [comment]
Another open question. In the flow [above](https://github.com/statechannels/statechannels/issues/2312#issuecomment-662699368), channel state is read in step 2 but updated in step 5. Are we susceptible to race conditions since the read is separated from the write. A couple ideas from @andrewgordstewart to avoid race conditions:
- Database constraints.
- Locking the channel.

**Comment by kerzhner** [comment]
RE [the race condition issue](https://github.com/statechannels/statechannels/issues/2312#issuecomment-662740581). The decision is to attempt per-channel locks to avoid race conditions. At the protocol start, a channel read lock is acquired. After the protocol runs (and potentially writes an update to the channel), the channel read lock is released.

**Comment by kerzhner** [comment]
Per discussions over the past couple days, we are no longer implementing this issue. If others disagree, we can reopen.
