### ISSUE TITLE
Direct funding protocol

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#2314]
If we believe that the app protocol and direct-funding protocol should be _separate_, then it might make sense for someone to independently being implementing the direct funding protocol.

@kerzhner and @snario both commented that using xstate for the browser wallet brought with it the benefit of _structure_. Hence, I explored two "structured" techniques for implementing protocols per [this document](https://www.notion.so/Copy-of-Wallet-Execution-Design-B-60806027072a46bdaf74c372436c9c89):
1. Using [xstate machines ](https://gist.github.com/andrewgordstewart/d1adecedd9d9d2cfa0ab5b99aa44aa17) to declare actions that should be executed, as you pass through states
2. Using a "[pattern matching](https://gist.github.com/andrewgordstewart/c7daea8bfc46e8b7bbf655cafed6f45d)" syntax

**Comment by andrewgordstewart** [comment]
I would vote for (2) over (1) because:
- xstate doesn't quite seem like the right tool for this: the protocols are not about managing state, they are about determining _what state you're in_
- xstate seems to add real developer cost: when I added `xstate` as a dependency and wrote [this code](https://gist.github.com/andrewgordstewart/d1adecedd9d9d2cfa0ab5b99aa44aa17), vs-code slowed down significantly: the Typescript server would spend seconds compiling the recursive types that `xstate` uses.

One suggestion might be to use `xstate/fsm`, which has no hierarchical states (and perhaps no recursive types?)

**Comment by davidkpiano** [comment]
@andrewgordstewart The next minor version of XState should have some notable improvements in TypeScript performance: https://github.com/davidkpiano/xstate/pull/1354

**Comment by andrewgordstewart** [comment]
stale
