### ISSUE TITLE
Rename monorepo to something wallet specfic

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#2330]
Now that we have the `apps` monorepo we should rename `monorepo` so it more accurately reflect what's left.

`wallet-monorepo` or `wallet` maybe?

**Comment by andrewgordstewart** [comment]
What about `statechannels`? (Since it contains more than just wallet-specific stuff)

**Comment by andrewgordstewart** [comment]
Done

**Comment by lalexgap** [comment]
> Done

I just realized that we're the `statechannels` organization, so this repo is `statechannels/statechannels` which is slightly confusing.
