### ISSUE TITLE
pushMessage does not return a ChannelUpdated outbox notification

### ISSUE THREAD

**Issue by snario** [statechannels/statechannels#2378]

**Comment by lalexgap** [comment]
I think that would be the responsibility of the `app` protocol (or another protocol?) that runs after the `Store` `PushMessage` runs.

The protocol could be responsible for 
- checking the type of channel (app, ledger, etc.) to determine if want to send out a notificaton
- Determine if we've signed the prefund setup or not
- create either a `ChannelUpdated` or `ChannelProposed` action.

The one downside is that the protocol isn't able to see the state of the channel before `PushMessage` so we won't be able to look at the changes to determine if we want to bother emitting a notification. Perhaps that's not an issue?

**Comment by lalexgap** [comment]
> I think that would be the responsibility of the `app` protocol (or another protocol?) that runs after the `Store` `PushMessage` runs.
> 
> The protocol could be responsible for
> 
> * checking the type of channel (app, ledger, etc.) to determine if want to send out a notificaton
> * Determine if we've signed the prefund setup or not
> * create either a `ChannelUpdated` or `ChannelProposed` action.
> 
> The one downside is that the protocol isn't able to see the state of the channel before `PushMessage` so we won't be able to look at the changes to determine if we want to bother emitting a notification. Perhaps that's not an issue?

Now I'm starting to wonder if the `Store` should just handle this. We could just change the `PushMessage` signature to return ` Promise<{channelIds: Bytes32[]; outgoing: SyncState}>` and it would be pretty trivial to do. I'm just wondering if the `Store` is taking on too much responsibility.
