### ISSUE TITLE
Server wallet stress test

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#2391]
The scenario we are preparing for this week is:

1. One payer client.
2. 20 receiver clients.
3. Many channels between one payer/receiver client.

## v0 stress test
- one payer client.
- one receiver client.
- 100 channels.
- A payer is requested to update all 100 channels at the same time.
- Success if all requests to payer receive responses in under 1s.

## v1 stress test
- one payer client.
- one receiver client.
- 100 channels.
- The payer is requested to sequentially update all 100 channels, 25 times, at the same time.
- Success if all requests to payer receive responses in under 1s.

There should also be a case where: (**not high priority** since this doesn't apply to the short term use case):
- The payer requests to update all 100 channels at the same time.
- The payer immediately requests to update all 100 channels at the same time, which should conflict with the previous requests 

## v2 stress test
- Same as v0 or v1, but with `n` payer and `n` receiver clients.

**Comment by snario** [comment]
One `pong`, one channel
- Call `ping` many times in a row on the same channel on the same `PingClient` without awaiting
- Call `ping` at the same time on 10 different `PingClients` for the same channel

One `pong`, many channels
- Call `ping` at the on every channel at the same time
- Call `ping` at the same time on 10 different `PingClients` for unique channels per client
- Call `ping` many times in a row on every channel at the same time
- Call `ping` at the same time on 10 different `PingClients` for every channel on every client

Many `pongs`, many channels
...
