### ISSUE TITLE
Audit SignState Usage

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#2406]
Profiling the pong server has revealed that we spend a lot of time in `SignState`. We should audit our calls to `SignState` to make sure we're only calling when necessary. 

See the flamegraph: 
https://statechannels.slack.com/files/UMXGSF1EY/F017WR84PD4/flamegraph.html

**Comment by andrewgordstewart** [comment]
I think we can get a quick win by only calling hash state once per state?

**Comment by andrewgordstewart** [comment]
This has been done!
