### ISSUE TITLE
XState-Wallet/ChannelProvider Sending Empty Objectives

### ISSUE THREAD

**Issue by SirNeural** [statechannels/statechannels#2454]
**Describe the bug :bug:**
Whenever a statechannel is first created, there are two initial messages sent from the host to the other participants:
1. An object containing an empty objectives property with a signedStates array of length 1, and
2. An object containing an "OpenChannel" objective and an empty signedStates array.
On the receiver end, this causes an error: Validation Error: Property at root.data.objectives should be array, which seems to stem from the message with an empty objective array.

**To Reproduce**
1. Go to monopoly.now.sh (need two different browsers with different metamask eth accounts)
2. Click on Create Room on one tab, and join on a different browser with the room code
3. Open DevTools and scroll down to see [https://i.imgur.com/Qzp0X5U.png](this message which wallet receives), and [https://i.imgur.com/H3vsobK.png](this error)

**Expected behavior**
I'm guessing that the wallet should be including an objective with each message, in this case its null for some reason and causing the error to happen on the receiver end when it parses it and doesn't find an objective.

**Screenshots (if applicable)**
[https://i.imgur.com/AmzCYKJ.png](host side messageSent, happens before channelUpdated is emitted)
[https://i.imgur.com/Qzp0X5U.png](receiver side messageReceived)
[https://i.imgur.com/H3vsobK.png](receiver side error)

**Logs (if applicable)**
Uncaught (in promise) Error: Validation Error: Property at root.data.objectives should be array
    validateMessage validator.js:51
    receiveRequest$ messaging.ts:206
    tryCatch runtime.js:45
    invoke runtime.js:264
    le runtime.js:98
    tryCatch runtime.js:45
    invoke runtime.js:137
    callInvokeWithMethodAndArg runtime.js:172
    callInvokeWithMethodAndArg runtime.js:171
    enqueue runtime.js:190
    le runtime.js:98
    async runtime.js:211
    receiveRequest messaging.ts:78
    pushMessage$ channel-wallet.ts:185
    tryCatch runtime.js:45
    invoke runtime.js:264
    le runtime.js:98
    tryCatch runtime.js:45
    invoke runtime.js:137
    callInvokeWithMethodAndArg runtime.js:172
    callInvokeWithMethodAndArg runtime.js:171
    enqueue runtime.js:190
    le runtime.js:98
    async runtime.js:211
    pushMessage channel-wallet.ts:25
    _callee2$/< index.ts:48
    sentryWrapped helpers.js:84
    _wrapEventTarget trycatch.js:89
    instrumentDOM instrument.js:402
    _callee2$ index.ts:44
    tryCatch runtime.js:45
    invoke runtime.js:264
    le runtime.js:98
    tryCatch runtime.js:45
    invoke runtime.js:137
    invoke runtime.js:147
    promise callback*invoke runtime.js:146
    callInvokeWithMethodAndArg runtime.js:172
    callInvokeWithMethodAndArg runtime.js:171
    enqueue runtime.js:190
    le runtime.js:98
    async runtime.js:211
    _callee2 index.ts:25
    596 index.ts:25

**Environment (if no logs are attached)**
 - Affected application(s) or package(s): Channel-Client/Channel-Provider
 - OS: Windows
 - Browser Latest Chrome + Firefox

**Comment by geoknee** [comment]
Thanks for posting this issue @SirNeural ! 

From what I can tell, the sending wallet is correctly sending a message with `objectives: undefined`.  The receiving wallet is correctly throwing an error when it gets a message with `objectives: null`. My suspicion therefore turns to your messaging layer (which I believe is webRTC). 

Could you try using `JSON.stringify()` to serialize the message before sending it through the messaging layer?

**Comment by geoknee** [comment]
For interest / completeness https://github.com/statechannels/statechannels/pull/2478/files

**Comment by SirNeural** [comment]
I can verify it is in fact an issue with the messaging layer, a JSON.stringify() solved the error for me. Thanks for the analysis!
