### ISSUE TITLE
Create integration test with two wallets communicating back and forth

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#2460]
Currently we don't have a test for testing the back and forth communication between wallets. It would probably be a good idea to have a test like that.

**Comment by andrewgordstewart** [comment]
Doesn't the e2e test do that?

**Comment by lalexgap** [comment]
> Doesn't the e2e test do that?

That's a good point, I forgot about that. Let me investigate.

**Comment by lalexgap** [comment]
> > Doesn't the e2e test do that?
> 
> That's a good point, I forgot about that. Let me investigate.

You're right, it looks like it's an issue in our `validateSignatures` function
