### ISSUE TITLE
Publish workflow failed

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#2497]
I followed the instructions [here](https://github.com/statechannels/statechannels/blob/master/readme.md#publishing-packages) to publish packages to npm.

When I did so, I got 
```
monorepo on  ags/publish-0.3.4 [$!] via ⬢ v12.16.3 on ☁️  us-west-1 took 21s 
❯ yarn lerna publish from-git
yarn run v1.22.4
$ /Users/andrewstewart/Code/magmo/monorepo/node_modules/.bin/lerna publish from-git
lerna notice cli v3.16.4
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna ERR! EUNCOMMIT  M packages/docs-website/website/versions.json
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The reason is that `docs-website` had a change that wasn't staged for commit:
```
monorepo on  ags/publish-0.3.4 [$!] via ⬢ v12.16.3 on ☁️  us-west-1 
❯ g s
On branch ags/publish-0.3.4
Your branch is up to date with 'origin/ags/publish-0.3.4'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   packages/docs-website/website/versions.json
```

I committed these changes, but then `yarn lerna publish from-git` failed:
```
monorepo on  ags/publish-0.3.4 [$+] via ⬢ v12.16.3 on ☁️  us-west-1 
❯ gcmsg 'Commit versions to docs-website'
husky > pre-commit (node v12.16.3)
lerna notice cli v3.16.4
lerna info Looking for changed packages since HEAD
lerna success run No packages found with the lifecycle script 'precommit'
[ags/publish-0.3.4 e87628bb2] Commit versions to docs-website
 1 file changed, 1 insertion(+)

monorepo on  ags/publish-0.3.4 [⇡$] via ⬢ v12.16.3 on ☁️  us-west-1 
❯ yarn lerna publish from-git
yarn run v1.22.4
$ /Users/andrewstewart/Code/magmo/monorepo/node_modules/.bin/lerna publish from-git
lerna notice cli v3.16.4
lerna notice from-git No tagged release found
lerna success No changed packages to publish 
✨  Done in 0.72s.
```

I tried to resolve the situation by
1. `git reset head~1`
2. stashing the unstaged changes
3. calling `yarn lerna publish from-git`
But it returned exit code 1:
```
lerna http fetch PUT 403 https://registry.npmjs.org/@statechannels%2fserver-wallet 480ms
lerna ERR! E403 You cannot publish over the previously published versions: 0.3.4.
```

@snario had already published the server-walelt package at version `0.3.4`.

**Comment by geoknee** [comment]
I'll take another look at this and see if I can improve the instructions. 

At least there is something apparently not right about those `gitHead: ...` fields that get added  https://github.com/lerna/lerna/issues/1880#issuecomment-456160357

**Comment by geoknee** [comment]
@andrewgordstewart could we publish [canary versions](https://github.com/lerna/lerna/tree/master/commands/publish#--canary) for updates targeted at certain consumers (such as a specific version of the server-wallet)? This would most likely avoid conflicts between lock-step version bumping and individual package version bumping.

**Comment by andrewgordstewart** [comment]
We should perhaps update the readme to include instructions for using canary versions, and then mark this as closed?

**Comment by andrewgordstewart** [comment]
Irrelevant, as we now have github actions to do this! 🎉
