### ISSUE TITLE
[client-api-schema] Error Structure

### ISSUE THREAD

**Issue by LayneHaber** [statechannels/statechannels#2504]
**Problem description :confused:**
The errors defined within the `client-api-schema` are currently defined on a per-method basis (i.e. all `UpdateChannel` errors are code `15xx`). This is helpful because you know the exact method the error is coming from when debugging, but doesn't allow for easy code reuse (i.e. `UpdateChannel` and `JoinChannel` have different errors for `Channel not found`).

**Describe the solution you'd like :rocket:**
***Error Structure***
Errors that represent the same core problem should be the same, and the `Error` object itself should provide sufficient information for debugging (including context like `method`). The object should have the following structure:

```typescript
type Error<T extends ErrorContext = unknown> = {
    code: number;
    context: T;
    message: string;
    method: string;
}
```

By separating the context and the code, you allow the code to represent the type or class of error encountered, while still retaining enough useful information to debug properly.

***Error Codes***
The error codes assigned to each error should follow a general [HTTP 4xx](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) error code mapping, substituting the 4xx prefix for a domain-specific 14xx prefix. While it is not explicitly necessary to model the codes after the HTTP error codes, doing so capitalizes on developers familiarity with the meaning of some codes (e.g. `x04` or `x03`). The major error codes are:

- `1400` -- invalid data supplied (i.e. bad parameters)
- `1401` -- unauthorized action
- `1403` -- forbidden action
- `1404` -- resource not found

**Describe alternatives you've considered**
***Domain Spaced Error Codes***
Another alternative is to create more domain-specific prefixes depending on what level of the stack the error was thrown from. In this paradigm, you would follow the similar HTTP suffix pattern described above and the prefix used would depend on the layer of the stack the error is coming from:
- `15xx State Errors` -- any errors related to the variable parts of a channel (not your turn, invalid state, etc.)
- `14xx Channel Errors` -- anything related to the fixed parts of the channel
- `13xx Message Errors` -- any errors related to parsing and handling messages
- `12xx Wallet Errors` -- any errors related to sending transactions, signing, recovery, etc.

The advantage here is that the error code becomes immediately more descriptive than when using the same domain prefix for all errors. However, the delineation between the stack layers may not be 100% clear and there become significantly more error codes to manage.

***Defining Errors By Method***
There is an argument to be made for defining all errors that each function could throw, and using that to define the errors that are thrown by the functions. I think that is a good exercise to make sure we understand the types of errors thrown at a high level, but will lead to more brittle types if we define the errors so explicitly.

**Additional context**
***Summary***
_Pros_
- Flexible error codes
- Code reuse across methods
- Makes use of existing developer knowledge (i.e. *04 error codes)

_Cons_
- HTTP may not be a direct mapping to our errors, so could cause some confusion
- Adding more detailed domain prefixes would give codes more richness (but may not be clear where to draw those lines)
- Defining errors from bottom up would allow us to be much more specific about the error definitions and RPC interface (but could lead to more brittle type defs)

***Errors by Method***
Example breakdown of errors by method:
CreateChannel
- Signing address not found (1404)
- Invalid participants (1400)
- Insufficient funds (1401)
- Unsupported/invalid token (1400)
- Invalid app definition (1400)
- Invalid app data (1400)

JoinChannel
- Channel not found (1404)
- Invalid transition (1403)
- Channel has invalid status (1403)

UpdateChannel
- Channel not found (1404)
- Invalid transition (1403)
- Invalid app data (1400)
- Not your turn (1403)
- Channel has invalid status (1403)

CloseChannel
- Channel not found (1404)
- Not your turn (1403)

DefundChannel
- Channel not found (1404)
- Not your turn (1403)
- Channel has invalid status (1403)

Withdraw
- Channel not found (1404)

Not your turn (1403)
- Channel has invalid status (1403)

ChallengeChannel
- Channel not found (1404)

GetChannels

GetState
- Channel not found (1404)

GetWalletInformation
- Signing wallet not found (1404)

PushMessage
- Participant not found (1404)
- Unauthorized (1403)

**Comment by geoknee** [comment]
I think we don't even need the `method` or `context` fields. The errors will be wrapped in the JSONRPC headers, which should be enough to infer enough context IMO -- namely, the error response will have an `id` that matches some request that was sent in. That request has a bunch of useful information including the `method`.

**Comment by LayneHaber** [comment]
We can get rid of the `method` field if that information is already included, but having the ability to return a JSON context object is important. Sometimes you may want to include information about the request (i.e. `channelId`) and other times you may want to return information from your store (i.e. `ChannelStatus` if joining fails, or `Adjudication` object if channel is in challenge)

**Comment by snario** [comment]
> _**Errors by Method**_
> Example breakdown of errors by method:
> CreateChannel
> 
> * Signing address not found (1404)
> * Invalid participants (1400)
> * Insufficient funds (1401)
> * Unsupported/invalid token (1400)
> * Invalid app definition (1400)
> * Invalid app data (1400)

1. Is insufficient funds actually applicable here? I don't think so, because that would happen at the time of funding.
2. What is an invalid app definition? Does it mean the wallet does not have the requisite bytecode?
3. What is invalid app data?
4. What is an invalid token? Unsupported makes sense, it would mean that there is no known `AssetHolder` for this token.
5. What about examples where there might be multiple asset holders for a particular token? How should we handle that?
6. What is the difference between invalid participants and signing address not found? Maybe it depends on the ordering? For example, you must always specify your participant address first if you are creating the channel (... I think? I guess not necessarily...)
7. What if multiple of these errors are spotted in a request, should we just return the first one that the wallet implementation found, or should we identify all of them? e.g., your signing address is missing, there is no bytecode for the app definition, and there is no known asset holder for the provided token in a single request?

**Comment by LayneHaber** [comment]
> 1. Is insufficient funds actually applicable here? I don't think so, because that would happen at the time of funding

May not be, the assumption I was making here was that in creating virtual channels, you would need to have sufficient funding in your ledger channel. That may not happen at channel creation, could be a misunderstanding on my end.

> 2. What is an invalid app definition? Does it mean the wallet does not have the requisite bytecode?

`0xbeef` is one we like to test, for example. This is mostly for input validation, and this could be unneccessary.

> 3. What is invalid app data?

`0xbeef` would probably count. Again, this is input validation.

> 4. What is an invalid token? Unsupported makes sense, it would mean that there is no known `AssetHolder` for this token.

An invalid address would count as an invalid token, input validation. The issue you mentioned could be a separate error, or we could fold it into this one.

> 5. What about examples where there might be multiple asset holders for a particular token? How should we handle that?

This is a good question, and I do not know the best answer since I'm not as familiar with your system. However, I can tell you from handling the `ProxyFactory` in counterfactual, if you have contracts that are associated with the channel for the lifetime of the channel, you should store those offchain and make sure they don't change. We added a `criticalAddresses` field to the channel data type to make sure this was permanently tracked. I don't know if your protocol has the same concerns, but this sounds like a versioning question.

> 6. What is the difference between invalid participants and signing address not found? Maybe it depends on the ordering? For example, you must always specify your participant address first if you are creating the channel (... I think? I guess not necessarily...)

I was not aware of the ordering, was specifically talking about participants with invalid `destination` or `signing` addresses (all 1400 codes are input validation errors). This is different than `Signing address not found` because that is referring to the address *you* need to create a channel, which should be in your store.

> 7. What if multiple of these errors are spotted in a request, should we just return the first one that the wallet implementation found, or should we identify all of them? e.g., your signing address is missing, there is no bytecode for the app definition, and there is no known asset holder for the provided token in a single request?

Hmm, as a user it seems much better to return all the errors at once rather than just hitting them one at a time. The only question I have there is how to handle the `code`, but I suppose we could do something like:

```typescript
type MultipleError = {
  code: 1450, // some random code
  message: "Multiple errors encountered",
  context: ChannelErrors[] // some object containing full error context
}
```

which I am a huge fan of (cc @geoknee )
