### ISSUE TITLE
[client-api-schema] Close/Defund/Withdraw API Finalization

### ISSUE THREAD

**Issue by LayneHaber** [statechannels/statechannels#2505]
**Problem description :confused:**
The current `client-api-schema` does not have a finalized close and defund JSON RPC interface defined for all environments.

**Describe the solution you'd like :rocket:**
The RPC interface itself should be unopinionated about default behaviors (in general, that's something that should be built as a higher layer abstraction), meaning the interface itself should have two distinct methods to mirror the two channel processes that must happen during the channel closing/defunding process: `close` and `defund`

```typescript
// Called on your turn to stop processing updates in channel
type CloseChannelParameters = {
    channelId: Bytes32;
}
type CloseChannelResult = ChannelResult;

// Called after channel is closed to retrieve funds. Because this may result in submitting
// an onchain transaction, it is important to not make any assumptions about the 
// desired application behavior between closing and defunding channels
type DefundChannelParameters = {
    channelId: Bytes32;
    amount?: Uint256; // default to total if not supplied
    destination?: Address; // default to Participant.destination if not supplied
}
type DefundChannelResult = ChannelResult;
```

The downsides of this approach are that it will take some more understanding of when to call the methods for most implementers to create the desired effect of "I close channel, I get money". Additionally, there are not many cases where you would want to partially withdraw from a virtual channel and it is not entirely clear what the `destination` would correspond to across all different channel types. However, it allows the RPC interface to mirror the protocol well, and leaves room for convenience RPC methods that are essentially wrappers around the above two that would get closer to the desired effect with one RPC call.

**Describe alternatives you've considered**
I haven't.

**Additional context**
***Summary***
_Pros_
- Clean API
- Mirrors core protocol requirements
- Extensible to partial withdrawals without types changes
- Leaves room to add more opinionated convenience methods (i.e. `CloseAndDefund`)

_Cons_
- Not clear in what cases you'd want to partially defund a virtual channel
- Not clear what `destination` maps to in virtual channel defunding

**Comment by snario** [comment]
I think we need to consider scenarios like the following:

- Defunding a virtual channel
- Defunding an application channel, into a ledger channel
- Defunding a direct channel
- Defunding an application channel, into a virtual channel

Also, separately, ask ourselves the question around what kinds of de-funding should be "automatic". That is, what should `pushMessage` and the Application Protocol automatically do given a state that is closed / unilaterally finalizable. Perhaps it should automatically defund into ledger or virtual channels, but perhaps also it should _not_ in the case of a direct channel?

**Comment by LayneHaber** [comment]
It seems to me that `withdraw` could be a wrapper method that is equivalent to `close + defund` but the core methods are simply `close` and `defund` themselves.

I'm hesitant to automate any behavior at the `ChannelWallet` layer, but I also can't think of many situations where you would want to have a closed or finalized channel holding money. I think that if the automated behavior could involve sending a transaction, it is best to give the application developers more granual control over how and when that transaction is submitted. For virtual or application channels, however, it is hard to think of a reason the channel shouldn't be automatically defunded once finalized.
