### ISSUE TITLE
[client-api-schema] PushMessage Behavior

### ISSUE THREAD

**Issue by LayneHaber** [statechannels/statechannels#2506]
**Problem description :confused:**
The `PushMessage` return value is currently defined as:

```typescript
type PushMessageReturn = {
    success: boolean;
}
```

Currently, this reflects the browser wallet implementations, where the return value indicates whether or not the message was properly saved. In the `server-wallet`, by contrast, `PushMessage` will return a `MultipleChannelResult` defined as:

```typescript
type MultipleChannelResult = Promise<{ outbox: Outgoing[]; channelResults: ChannelResult[] }>;
```

**Describe the solution you'd like :rocket:**
The behavior from the `PushMessage` rpc method should be environment agnostic. I'm not sure the best way to include the `outbox` information from the `server-wallet`, but it seems the general pattern should be to return something more similar to the `MultipleChannelResult` instead of the current `boolean` value.

It's possible that the browser wallets could also easily incorporate the `outbox` field, but if not i think the best route is to return an object of the type:

```typescript
type PushMessageReturn = {
    channelResults: ChannelResult[];
}
```

**Describe alternatives you've considered**
None

**Additional context**
***Summary***
_Pros_
- Consistent rpc interface across wallet environments
- Easily interpretable results
- Can be extended depending on the wallet interface

_Cons_
- Likely not optimized for the environment
- `outbox` field does not easily map between environments

**Comment by snario** [comment]
Curious what @tomclose and @andrewgordstewart think about the browser wallet adopting the server-wallet's push message signature
