### ISSUE TITLE
[client-api-schema] GetChannels API

### ISSUE THREAD

**Issue by LayneHaber** [statechannels/statechannels#2507]
**Problem description :confused:**
The `GetChannels` parameter currently only includes one field (`includeClosed`) to filter channel return values. Because the channel storage is so tightly coupled with the rpc interface, including other ways to filter query results would improve app performance.

**Describe the solution you'd like :rocket:**
The `GetChannels` parameters should be treated as a query object:

```typescript
type GetChannelsRequestParameters = {
  participants?: Participant[]; // string[] for participantIds?
  channelId?: Bytes32;
  status?: ChannelStatus[];
  appDefinition?: Address;
  ...
};
// alternatively
type GetChannelsRequestParameters = Partial<Omit<ChannelResult, "status"> & { status?: ChannelStatus[] }>
```

where each provided field acts as a query parameter. 

**Describe alternatives you've considered**
You could add independent rpc request methods for each of the getters, but this would be brittle, and would increase the number of shallow methods within the interface.

**Additional context**
***Summary***
_Pros_
- Maps cleanly to other types
- Keeps the interface definition clean

_Cons_
- May end up changing the method parameters
- Not as readable

**Comment by geoknee** [comment]
@snario @LayneHaber  I have a couple of questions about this:

> **Problem description 😕**
> The `GetChannels` parameter currently only includes one field (`includeClosed`) to filter channel return values. Because the channel storage is so tightly coupled with the rpc interface, including other ways to filter query results would improve app performance.

As far as I am aware, we haven't yet hit issues with app performance via this RPC method. In fact, apps ordinarily learn about channels by listening to the  `ChannelUpdated` notifications. Are there use-cases you have in mind that make this necessary/urgent?

> 
> **Describe the solution you'd like 🚀**
> The `GetChannels` parameters should be treated as a query object:
> 
> ```ts
> type GetChannelsRequestParameters = {
>   participants?: Participant[]; // string[] for participantIds?
>   channelId?: Bytes32;
>   status?: ChannelStatus[];
>   appDefinition?: Address;
>   ...
> };
> // alternatively
> type GetChannelsRequestParameters = Partial<Omit<ChannelResult, "status"> & { status?: ChannelStatus[] }>
> ```
> 

So you're allowing the app to pass an array of values for `status`. I imagine this is to allow the app, for example, to express that it wants a `ChannelResult` for all channels where the status is `challenged` OR `closed`. Why stop at `status`? You could do 

```ts
type Query<T> = {
    [P in keyof T]?: Array<T[P]>;
}
type GetChannelsRequestParameters = Query<ChannelResult>
```

I can see this snowballing, though. How do I express that I want all channels where the participants array is `participantsA` AND the status is `open` OR the participants array is `participantsB` AND the status is `closed`? Should this kind of query even be supported? Again I think the answer depends on understanding use-cases that we have (or anticipate) a bit more. 

To develop this into a proper query language, you should also be able to specify which fields you want in the result, i.e. something other than  `ChannelResult[]`. I'm a little wary of embarking on that kind of effort if we could get away with just piping everything to the app and have the app filter the data itself. 

Maybe there's a middle ground or compromise to be struck? Say, we just use `Partial<ChannelResult>` for the request and `ChannelResult[]` for the response? Im not sure but maybe we can kick off a discussion.

**Comment by snario** [comment]
I think this isn't _urgent_ but worth documenting some thoughts around. Maybe @LayneHaber has a use case where the number of channels simply cannot be held in memory?

**Comment by LayneHaber** [comment]
Sure, one example is retrieving a both sides of an offline payment (i.e. a payment that is made across two ledger channels and locked via hashlock instead of being performed in a virtual channel). The sender would create an application in their channel with the intermediary, who would wait until the recipient came online. Once they did, the intermediary would install the application, and the recipient would update + close app. 

Now in order to break even, the intermediary must find the channel with the sender and update it. Because the recipient could have taken indefinitely long to come online, theres no guarantee the intermediary is still holding the channel with the sender in memory (what if you shut down your server to push an update?). In this case, especially because the intermediary would have so many channels, grabbing all the channels is not a good idea.

Additionally, we've found many messaging services break down when handling super large payloads (like pulling all the open channels from the store), so we'll definitely want to make sure the return results are limited where we can

**Comment by snario** [comment]
> In this case, especially because the intermediary would have so many channels, grabbing all the channels is not a good idea.

What is _so many_ here?

**Comment by LayneHaber** [comment]
If you consider a use case the size of the graph runs a hub, it could be several hundreds of thousands of ledger+virtual channels depending on how they structure the payments
