### ISSUE TITLE
[client-api-schema] Wallet Getters

### ISSUE THREAD

**Issue by LayneHaber** [statechannels/statechannels#2508]
**Problem description :confused:**
Right now there is a `GetWalletInformation` method that returns the generic channel participant information (signing address, destination address) as well as the wallet version number. This method doesn't easily map to other types used in the interface, or to the usage of ephemeral keys*.

**Describe the solution you'd like :rocket:**
It would be better to split this out into two methods, with the following type defs:

```typescript
// Return your `Participant` information for a given channel
type GetParticipantInformationParameters = {
   channelId: Bytes32;
}
type GetParticipantInformationReturn = {
    participant: Participant;
}

// Return version numbers
type GetVersionNumberParameters = {}
type GetVersionNumberReturn = {
    walletVersionNumber: number;
}
```

**Describe alternatives you've considered**
I haven't.

**Additional context**
***Summary***
_Pros_
- Maps easily to existing types
- Allows space to version other things (i.e. protocol messaging) in the future
- Maps cleanly to ephemeral keys*

_Cons_
- Adds an additional method to the interface
- Participant information requires a `channelId`

***NOTE**: I do **not** advocate for the use of signing keys per channel, for a variety of reasons that are out of the scope of this issue. However, because the protocol itself does allow for it I think it should be reflected in your rpc interface.

**Comment by snario** [comment]
I agree with the separation of `GetParticipant` and `GetVersion`. Keep in mind that `destination` could be `undefined` if, in the browser context, the ethereum provider is not enabled, or for some reason (e.g., MetaMask is locked), is not sharing the user's ethereum address.

**Comment by LayneHaber** [comment]
Sure, though I think that really that should be done with a different field name. 

It seems like you're abusing the property if you check whether or not ethereum is enabled like that

**Comment by snario** [comment]
> It seems like you're abusing the property if you check whether or not ethereum is enabled like that

Why?

**Comment by LayneHaber** [comment]
`destination` does not seem to have anything inherently to do with triggering `EnableEthereum`, so knowing that if the `destination` is `undefined`, then I have to call `EnableEthereum` seems like insider knowledge, or at least that it could be clearer.

Keep in mind, I'm not as familiar with the browser packages, so I'm not sure what the `EnableEthereum` endpoint does and how it corresponds to `destination` at all

**Comment by snario** [comment]
In the browser wallet, we use the first account in your MetaMask wallet that is "connected" to the page as your `destination` — once set, it never changes, and is forever locked as that address. It seems reasonable to want to change that, especially if you switch accounts on MetaMask, but there is a usability hurdle there for the wallet.
