### ISSUE TITLE
[client-api-schema] Channel Status

### ISSUE THREAD

**Issue by LayneHaber** [statechannels/statechannels#2509]
**Problem description :confused:**
Currently the channel has a single status is defined as:

```typescript
export type ChannelStatus =
  | 'proposed' // The wallet is storing this channel, but you have not joined it -- ie. you have not yet signed a state.
  | 'opening' // You have joined the channel, but it's not ready to use.
  | 'funding' // Same as 'opening'?
  | 'running' // You are free to use the channel.
  | 'challenging' // You cannot use the channel right now. There is a challenge ongoing, but you do not need to do anything.
  | 'responding' // There is a challenge ongoing, and you must call `updateChannel` in order for the wallet to respond to the challenge.
  | 'closing' // You cannot use the channel anymore, but your funds are still locked up.
  | 'closed'; // Your funds have been released from the channel.
```

see discussion in #2432 

**Describe the solution you'd like :rocket:**
In previous discussions, the idea of breaking up the single channel statuses into three distinct status enums. I think making the statuses more granular is most helpful, and using a global channel status can be confusing specifically around channel deposits and withdrawals. Instead, these fields would be more descriptive:

```typescript
type AdjudicatorStatus = {
   | 'challenging' // challenge is ongoing
   | 'responding' // your turn to respond in a dispute
   | 'finalized' // challenge has been finalized onchain
   | 'none' // challenge cleared or not initiated
}
type ChannelStatus = {
   | 'created' // channel has been created, waiting for join
   | 'joined' // channel has been joined, ready to fund
   | 'funding' // channel is waiting for an onchain deposit
   | 'defunding' // channel is waiting for an onchain withdrawal
   | 'running' // channel is operational
   | 'closed' // channel is closed
}
```

and the `ChannelResult` type would have a field for each of these statuses. In our experience, depositing and withdrawing are most likely to break a channel (there could be a variety of reasons for that, think yam launches again and you hardcoded your gas price) inadvertently. There is no great general pattern for recovering from this, though incorporating a way to do that would be great, so many recoveries have to be manual. This means you need a crystal clear idea of what transaction the channel was waiting for, so you can determine the best way to recover safely.

**Describe alternatives you've considered**
I haven't.

**Additional context**
***Summary***
_Pros_
- Clear delineation of statuses
- Easily maps to top-ups and partial withdrawals
- Can easily track where funding + defunding failed (especially important for onchain transactions)

_Cons_
- Doesn't always clearly map to the rpc requests (i.e. could be `proposed` instead of `created` or `closed/defunded` instead of `closing/closed`
- Funding status is much more important for ledger channels than for application/virtual channels
- There are now 3 different statuses on a single channel

**Comment by snario** [comment]
This is pretty close to what I was thinking previously. I'm not sure what `withdrawing` means. Seems like we also need ` funded` type above.  Also the `//` comments seems mismatched for some of them above.

**Comment by LayneHaber** [comment]
>  comments seems mismatched for some of them above

Oh you're totally right, my bad!

> I'm not sure what withdrawing means. Seems like we also need funded type above.

So, this is more to indicate what would *type* of onchain transaction you're waiting on, but is not strictly necessary. I'm not sure how the `funded` type maps clearly to top-ups though

**Comment by snario** [comment]
I think top-ups are likely a higher order operation than what you would do with a `Channel`. It's what we would call a "workflow" that manipulates channels in order to achieve some effect; in this case moving more money on-chain or from some other channel into a new channel.

**Comment by andrewgordstewart** [comment]
Can you edit the comments to reflect their intended meaning?

**Comment by LayneHaber** [comment]
> I think top-ups are likely a higher order operation than what you would do with a Channel. It's what we would call a "workflow" that manipulates channels in order to achieve some effect; in this case moving more money on-chain or from some other channel into a new channel.

We can probably offload some of this monitoring to the onchain service/application layers, so it's probably redundant here. I removed the `FundingStatus` from the status proposals, and updated some of the channel statuses to reflect that.

> Can you edit the comments to reflect their intended meaning?

Yes! Also updated the proposal itself based on the comments so far.
