### ISSUE TITLE
[client-api-schema] Finalize JSON RPC API

### ISSUE THREAD

**Issue by LayneHaber** [statechannels/statechannels#2510]
## Feature Description
Right now the `client-api-schema` package contains the parameter, response, error, and request types for the JSON RPC interface used to communicate with the channel wallet. As it stands, this rpc interface isn't completed or consistent between the wallet implementations. There are a few items to come to consensus on, see: #2504 #2505 #2506 #2507 #2508 #2509 

## Rationale
Once the JSON RPC interface is defined, we are able to build out mocks to make progress on the `server-wallet` and our `nonrouting-node` implementation simultaneously.

## Additional Context
A finalized JSON RPC spec will be created [here](https://github.com/connext/statechannels/blob/client-api-docs/packages/docs-website/docs/protocol-docs/client-specification/json-rpc-api.md)

**Comment by snario** [comment]
I'd be curious to see how far these mocks can be built out with the existing APIs we have, and which of these issues are in fact blocking

**Comment by LayneHaber** [comment]
I mean we're going to start building out against what is there and the methods we have a strong idea are finalized regardless. But the further along we get the more may change with these lower level changes, so definitely very high priority to get this finalized
