### ISSUE TITLE
[server-wallet] Deposit to address

### ISSUE THREAD

**Issue by LayneHaber** [statechannels/statechannels#2516]
## Feature Description
User should be able to send their funds directly to an address as a way of funding the channel

## Rationale
Within the counterfactual protocol, all funds can just be sent directly to an address that represents a multisig (which can be deployed on channel creation or at the time of withdrawal). The ability to do fund the channel this way makes channel interactions much smoother.

## Additional Context
There was talk of being able to use a sort of `Boomerang.sol` contract to do this, but I'm not sure how that would work.

**Comment by snario** [comment]
> The ability to do fund the channel this way makes channel interactions much smoother.

Which interactions specifically?

**Comment by LayneHaber** [comment]
So imagine a user has some funds on an exchange and they want to use that money to fund a channel (or, we want to allow channels to be funded directly from Wyre).

In this scenario, there's three options:
1) _User is able to send funds directly to an address and fund the channel._ This is a good userflow with the minimum number of onchain transactions. It is also a desirable property because it also means exchanges wouldn't have to build anything else to support a channel integration.

2) _User sends funds to some address they control, then fund the channel from there._ This will definitely result in some users losing funds in the shuffle, not to mention the added onchain tx.

3) _Exchange has channel integration, and user can initiate a channel deposit through them._ Without the ability to send to an address, each exchange will have to build custom code to support this functionality.

**Comment by snario** [comment]
There seem to be a few ways you can accomplish this.

1. Create a contract wallet that, when receiving funds (via the fallback function), forwards those funds directly into a channel. This could be a done either by making the contract wallet itself an asset holder, or by forwarding funds into an asset holder (which may incur higher gas fees)

2. Deploy a multisig wallet and use that as the asset holder, which would require making changes to the wallet such that it treats funds inside of the multisig as valid funding. Probably requires some kind of plugin that treats pre-signed multisig transactions as valid as on-chain deposit events
