### ISSUE TITLE
[server-wallet] ChannelSigner support

### ISSUE THREAD

**Issue by LayneHaber** [statechannels/statechannels#2518]
## Feature Description
Support for a specialized `ChannelSigner` class, an example defined [here](https://github.com/connext/indra/blob/staging/modules/utils/src/channelSigner.ts), within the wallet.

## Rationale
Most wallets will not support exposing a mnemonic or a private key, or a signer with general functionality. A better pattern is to create a specialized channel signer that can be passed into any channel wallet. The signer should have restricted functionality, and only be able to sign channel-prefixed messages.

## Additional Context
This may impact more packages than just the `server-wallet` and I can help implement those changes as needed.

**Comment by snario** [comment]
What is the purpose of this? From the point of view of a state channels wallet, the key which signs states is irrelevant as long as it is consistent. Perhaps this is related to the fact that you want a single public identifier which can be used to decide what key your counterparty will be signing with when you construct a new channel?

**Comment by LayneHaber** [comment]
Using a `ChannelSigner` is important for the following reasons:
- Allows wallets to inject a signing object instead of a raw private key/mnemonic
- Doesn't support generic signing, so the damage a compromised `ChannelSigner` can do is mitigated
- Allows us to create a highly optimized signer (using special crypto utils)
- Allows us to create a globally unique identifier that is tied to a public key

The first two reasons are very important if you want wallets to feel comfortable integrating with a channel wallet

**Comment by snario** [comment]
> Allows wallets to inject a signing object instead of a raw private key/mnemonic

Why do they need to inject anything at all?

> Doesn't support generic signing, so the damage a compromised ChannelSigner can do is mitigated

If they don't inject anything at all, there is no damage at all

> Allows us to create a highly optimized signer (using special crypto utils)

Why not make the wallet highly optimized anyway?

> Allows us to create a globally unique identifier that is tied to a public key

Don't you already get this with the `signingAddress` created by a randomly generated signing key when the wallet is first initialized?

**Comment by pedrouid** [comment]
> Why do they need to inject anything at all?

Key generation can be tied to the integrator's system. Example: deterministically generating keys per channel based on a derivation.

Providing a ChannelSigner interface allows signing to be decoupled from the server-wallet. Example: proxying signing through a JSON-RPC interface.

> If they don't inject anything at all, there is no damage at all

True, but then you loose the two benefits described above. Providing custom signing (meaning custom serialization with dedicated prefix) allows to mitigate auto-signing something that isn't State Channel related with the same curve.

> Why not make the wallet highly optimized anyway?

The point here again is allowing to decouple signing from the server-wallet to allow native cryptography to be used isomorphically (maybe not as relevant for the server-wallet but definitely more relevant for Browser and Mobile apps)

> Don't you already get this with the signingAddress created by a randomly generated signing key when the wallet is first initialized?

Address would be the hash of the publicKey. The current public identifiers that we use for Connext v7.0 are using the following schema: `"indra" + base58(publicKey)`. This allows us to both easily recognizable identifiers for our network while maintaing the public key used for encrypting screts shared only between two parties in a transfer

**Comment by bohendo** [comment]
> Why do they need to inject anything at all?
In general, it's not best practice to save private keys to a db in cleartext. By injecting the key, we can keep it in memory. **The key never needs to touch the disk.**

A lot of crypto teams are superstitious control freaks about private keys & will want the option to manage them themselves. Or someday, a company might want their keys managed by some 3rd party enterprise-grade key management specialist. We really ought to give people the option to manage their keys however satisfies their superstition & then inject it into their state channel wallet.

I don't have super strong feeling whether we inject a raw private key or a wrapped signer though.

**Comment by snario** [comment]
First, a clarification: the keys that you use for signing state channel states do not necessarily need to have any relation whatsoever to any sort of public identifier that you use for letting others know who you are in a network. They do not need to be funded with any ETH nor do they need to have any ties to any on-chain state at all.

Okay, so then there seem to be a few concerns:

1. **How do we ensure signing is fast?** I don't think there is any scenario where we wouldn't use the fastest possible signing implementation that can exist in the environment that any wallet we write exists in. Right now we have two wallets, one written for a NodeJS environment and the other for a web browser. We [recently started](https://github.com/statechannels/statechannels/pull/2482) using `libauth` and got a 2x speed up in NodeJS for example. Someone could make a PR to use some WebAssembly code and get more of a speedup.

2.  **How do we ensure the keys are safe?** Again it seems like this is a critical responsibility of this piece of software. It is signing states all the time — by definition it needs to have access to one or many private keys to sign states with. Right now we store that private key inside of a PostgreSQL database on NodeJS and IndexedDB on the web. Should it be up to this project to decide where these keys are stored, or should it be up to the developer that uses these packages? There are also certainly decisions we can make to maximize the security of these keys like encrypting the data at rest with a password that needs to be provided on startup for example. What are examples of other similar pieces of software and how they handle this?

3. **How does someone know what `signingAddress` to use for a new Channel?** In Counterfactual I designed a system that uses an extended public key _as the `participantId`_ for a channel, and then `signingAddress` was determined as the `k`-th derived public address of that extended public key. The `node` software stored the extended _private_ key which it could use to get the corresponding `k`-th derived private key. This had the nice benefit that for _all channels_ you just needed to know someones extended public key in order to send them a proposal for a new channel to be created.

    With State Channels / @statechannels, we do things differently. A wallet generates a `signingAddress` and decides on a `participantId` separately. In fact, wallets don't really care what their `participantId` is — it's more of an application-specific concept. For example, in Web3Torrent you want to use the Bittorrent Peer ID concept. In Rock Paper Scissors, something like "bob" and "alice" (i.e., since messaging is done using Firebase). In Connext, maybe the extended public key is the right ID. I don't think we've really explored the possible design space of how to handle addressing of participants, but it seems fundamental to a wallet since it must determine `MessageQueued`s to be sent out, and handle `pushMessage` API calls both with arbitrary `sender` and `recipient` values.

    Anyway, right now we require applications share the `signingAddress` when creating any sort of implementation for their applications to do "peer discovery". The app must use _both_ the `participantID` and the `signingAddress`. I think there is a tradeoff to consider in fact — if these two things were one value, the extended public key, then the application must handle creating an "address book" that maps these values to messaging addresses. For example `xpubabc... => http://server.com/bob`. If they are separate, then the Wallet can emit something like `{ to: 'http://server.com/bob', ... }`.

**Comment by tomclose** [comment]
Thanks for sharing these perspectives. It makes sense to me that injecting a signer - or at least allowing integrators to  manage/store their own private keys - is a use case that we should support.

In the short-term, I think we should also support the existing pattern, where the state channel wallet generates its own key(s), and takes responsibility for storing it(them). The power of these "ephemeral" keys are strictly limited to the funds held within the state channel, so it might be a reasonable tradeoff to store them on disk with the states, assuming that the value stored is low. That way, the wallet is responsible for everything you need to continue participating in a channel.

I also wanted to re-iterate a couple of the points that Liam made. Firstly, we support arbitrary identifiers (`participantIds`), which would allow globally unique public ids tied to public keys, regardless of whether signers are injected or not. Secondly, we'd probably want to figure out how best to optimize crypto operations anyway, as there are non-signing-related operations (hashing and signature recovery), which we need to perform that (presumably) wouldn't be part of the injected signer?

We could probably get a v0 working by adding the `persistKeys` option, and using the existing functionality for initializing a wallet with a set of `privateKeys`. With `persistKeys = false` these keys would be stored in memory only. The integrator would take responsibility for passing in the same private key(s) each time the wallet was started.

Interested to hear if this would be sufficient for the time being? Also willing to investigate injecting the signer, but I think this will require more re-plumbing. It seems like the thing you gain here is that the integrator can restrict the format of the data that the key signs. Do people generally agree that this is only an issue if your state channel is using a key that is also used for another purpose?

**Comment by pedrouid** [comment]
> libauth and got a 2x speed up in NodeJS for example

Thanks for sharing about bitauth... I will take a look at the performance compared to what we are correctly using. Looking at the PR you shared it seems you are comparing ethers with bitauth which    explains the major performance increase. We are using node-secp256k1 in our default ChannelSigner implementation.

> Web3Torrent you want to use the Bittorrent Peer ID concept

Interesting but in that case how you manage a mapping between participant ID and channel wallets, right? For simplicity we use the publicIdentifiers which are the public keys themselves for the channel wallet. Correct me if Im wrong

> was determined as the k-th derived public address of that extended public key.

we actually moved away from xpub and are only using a single. public key from a keypair

> We could probably get a v0 working by adding the persistKeys option, and using the existing functionality for initializing a wallet with a set of privateKeys. With persistKeys = false these keys would be stored in memory only. The integrator would take responsibility for passing in the same private key(s) each time the wallet was started.

This would definitely be sufficient for a first iteration. IMO when we migrated from managing private keys to ChannelSigner interfaces it created a stronger separation of concerns between the key management and the counterfactual protocol

**Comment by snario** [comment]
> Interesting but in that case how you manage a mapping between participant ID and channel wallets, right? For simplicity we use the publicIdentifiers which are the public keys themselves for the channel wallet. Correct me if Im wrong

This is implicit — if you receive a message, you assume the message was addressed to you, and you push it into your wallet.

**Comment by pedrouid** [comment]
I see...  the separation of signing and messaging makes it redundant for an implementer to stick to a strict mapping. That makes sense.
