### ISSUE TITLE
[nitro-protocol] Insufficient event information in `respond`

### ISSUE THREAD

**Issue by LayneHaber** [statechannels/statechannels#2526]
**Describe the bug :bug:**
In the `respond` function of `ForceMove.sol` the challenge is cleared and the data emitted from the `ChallengeCleared` event is not verbose enough to create a new state in the application (as opposed to `ChallengeRegistered`). Consider the following scenario:

- A and B have a channel together, where B is the turn taker at nonce `n` and A has already sent a signed `n-1` to B
- B becomes malicious and stops responding, A wants to get their funds out of the channel
- A starts the challenge by calling `forceMove` with state `n-1`, the `ChallengeRegistered` event is emitted
- B calls `respond` to clear the challenge with some state `n`, the `ChallengeCleared` event is emitted

A could determine the data sent to `respond` by parsing the calldata, but this is much less intuitive than using existing events to capture channel information.

Instead, the `respond` should also emit a `ChallengeRegistered` event instead of only a `ChallengeCleared` event.

**Comment by HeikoFisch** [comment]
A similar situation applies to the `checkpoint` function, which also introduces new state information without emitting event data accordingly.

**Comment by snario** [comment]
@LayneHaber @HeikoFisch The data is included in the transaction argument

**Comment by LayneHaber** [comment]
I would be in favor of adding it to the event data, it's usually a lot easier to parse vs pulling it from the transaction data. Also seems a bit antipattern to pull it from the transaction when you use events so much more frequently throughout your protocol

**Comment by snario** [comment]
It's not really inconvenient to fetch it if you have access to the block data, and it's more gas efficient to do it this way. I think it depends on whether or not this behaviour is "too weird" for a service like The Graph to handle it via its query language for example though.

Let's say I have a chain watcher and I start it up 10 blocks after a response event was emitted. Is there any strategy for historical data syncing where accessing this data is particularly hard?

**Comment by LayneHaber** [comment]
I'm not super familiar with actually setting up the graph (cc @rhlsthrm) but ethers obviously makes it relatively easy to get the historical logs. 

Right now what we do in our chain listener is pretty simple, we save the block the channel was created and start historically syncing events from there on start in chunks, and save where we last synced. It's definitely not the most efficient way to do this, and I would advocate for other strategies, but it does work

**Comment by rhlsthrm** [comment]
> I think it depends on whether or not this behaviour is "too weird" for a service like The Graph to handle it via its query language for example though.

I believe we would be able to build a subgraph that contains logic to build out the entities using the transaction data, so this probably isn't a problem. It might be worth trying this though.

**Comment by bohendo** [comment]
> The data is included in the transaction argument — this is how it has been handled in the past.

Do you have example code of this being handled? My gut reaction is that trying to extract & properly encode info from calldata is going to be an ugly, fragile can of worms but seeing a nice example of this would help to put my mind at ease.

You all have done a really great job of optimizing gas throughout the solidity codebase. I think this is one place where we should relax though, let's let [the massive 4x cut to gas costs made in a previous refactor](https://github.com/connext/statechannels/blob/master/packages/nitro-protocol/notes/blog-posts/gas-optimizations/gas-optimizations.md) pay a small fee here for what's, IMO, a massive improvement to developer experience.

**Comment by snario** [comment]
Here is an implementation in `nitro-protocol`: https://github.com/statechannels/monorepo/blob/f3095a4b6ec48ba7a07035e06d6f3841620a5ae5/packages/nitro-protocol/src/contract/challenge.ts#L94-L137

**Comment by tomclose** [comment]
The pattern of providing data only in CALLDATA seems to be gaining traction in Ethereum - both ORUs and zk-rollups use this approach.

**Comment by HeikoFisch** [comment]
I assume then the reason why the `ChallengeRegistered` event is more verbose and _does_ contain information that could, in principle, be derived from calldata is to make it easier for third-party services like watchtowers to react to a laid out challenge?

**Comment by snario** [comment]
Looks like I added it [back in October 2019](https://github.com/statechannels/statechannels/pull/176) naively — probably thinking the same thing that motivated this Github issue

**Comment by HeikoFisch** [comment]
:slightly_smiling_face: Ok, thank you! I was just curious...

**Comment by geoknee** [comment]
See linked PR for an indication of gas costs if we go down this route. My feeling is that we actually want to go in the opposite direction and thin out the information that is emitted in our events. But we should provide JS helpers in `nitro-protocol` roughly along the lines of @snario's suggestion, to encapsulate the complexity involved in scraping information out of CALLDATA.
