### ISSUE TITLE
channelProvider.mountWalletComponent(...) fails if there is a trailing slash on the url

### ISSUE THREAD

**Issue by ditchfieldcaleb** [statechannels/statechannels#2563]
**Scope**: mounting the x-state wallet as per the instructions in the [quick start - dapp](https://docs.statechannels.org/app-devs/quick-start-dapp) section

**Summary**: Mounting the wallet component as per the instructions fails unless the trailing slash is removed from the x-state wallet URL - ie "https://xstate-wallet.statechannels.org/" --> "https://xstate-wallet.statechannels.org"

**Steps to reproduce the behavior:**
1. Create a simple app following the instructions as per the [quick start](https://docs.statechannels.org/app-devs/quick-start-dapp)
2. Bundle/webpack/etc and serve a compiled simple app with a button to enable the wallet

My suspicion is that this issue is due to CORS or some other cross-origin problem, and that the trailing slash changes enough of the URL such that it is deemed as "other/unsafe". From the few hours of debugging I did on this, it seems that the wallet does start up correctly inside of the iframe, but the `postMessage` event either never gets sent from iframe --> parent, or is sent and not picked up by the parent/blocked.

Note that even without the slash, the `await` call still never returns - see issue #2564

**Comment by geoknee** [comment]
@ditchfieldcaleb Thanks for pointing this out. The linked pull request updates the docs to not include the trailing slash, which shouldn't be there. 

For good measure it also changes the `iframe-channel-provider` to normalise the url passed in, so that in future this won't cause problems.
