### ISSUE TITLE
Ganache does not start on Windows

### ISSUE THREAD

**Issue by HyperCharlie** [statechannels/statechannels#2622]
When trying to start xstate-wallet on Windows, after installing from NPM, ganache fails to startup because of a problem in NodeJS' spawn() function.

I tried to make a PR for you but did not have the permissions to push a branch. The fix is pretty easy. In statechannels/packages/devtools/src/ganache/server.ts, on line 153, change:

`this.server = spawn('npx', ['-c', cmd], {stdio: 'pipe'});`

to 

`this.server = spawn('npx', ['-c', cmd], {stdio: 'pipe', shell: true});`

**Comment by geoknee** [comment]
Thanks for this @HyperCharlie! Have linked a pull request that makes the change you suggest.

**Comment by geoknee** [comment]
Tests are failing for that PR, will have to investigate.

**Comment by HyperCharlie** [comment]
@geoknee, on my local, it looks like the startup is inconsistent. yarn start-xstate-wallet (might be mixing up my yarn commands between yours and ours, but it should be xstate-wallet start) only gets to start.js maybe 50% of the time. Other times it fails totally silently. I mean, I'm getting nothing.

**Comment by geoknee** [comment]
It's possible (probable, even) that ganache is not being shut down properly after the first time you ran the command.   We should fix that, but in the mean time you could try finding that process and killing it before running the command again?

**Comment by geoknee** [comment]
I *think* the issue should be fixed, but we'll need to publish a new patched version to `npm`, and get someone who has a windows machine (not me!) to verify. We can reopen if not.
