### ISSUE TITLE
Server wallet: pushMessage should only return one channelResult per channel

### ISSUE THREAD

**Issue by tomclose** [statechannels/statechannels#2623]
### Expected behaviour
Calling `pushMessage` on the server wallet should never contain more than one `ChannelResult` for each channel. This `ChannelResult` should represent the state of the channel at the end of the `pushMessage` operation i.e. after all actions have been taken and the run loop has terminated.

### Actual behaviour
Currently `pushMessage` sometimes returns more than one `ChannelResult` per channel. In the `PaymentManager` I'm running into a case where the `ReceiptManager` provides a payload that contains states 0 and 3 in a given channel. The response from `pushMessage` contains three `ChannelResults`.

**Comment by andrewgordstewart** [comment]
Are the three results identical?

**Comment by tomclose** [comment]
They appeared to be. I think that might be chance though, because the 3 state doesn't have any affect on the channel state, because the channel isn't funded yet(?). I'm not entirely sure and haven't had time to fully investigate.
