### ISSUE TITLE
[xstate-wallet] Missing dependencies

### ISSUE THREAD

**Issue by geoknee** [statechannels/statechannels#2627]
There are apparently still some missing dependencies in `package.json` that means these instructions do not work at present. At least that should be fixed before merging this.

_Originally posted by @geoknee in https://github.com/statechannels/statechannels/pull/2598#issuecomment-699009277_

**Comment by geoknee** [comment]
After trying to fix this, I am seeing the following error: 
```
➜  xstate-wallet git:(depcheck) ✗ yarn build
yarn run v1.22.4
$ node scripts/build.js
Creating an optimized production build...
Failed to compile.

./src/ui/wallet.scss
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'plugins'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap? }


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: /Users/georgeknee/.yvm/versions/v1.22.4/bin/yarn.js build
```

**Comment by ditchfieldcaleb** [comment]
@geoknee related to this issue, I had to run a `npm install postcss postcss-loader` inside of the `xstate-wallet` package in order to fix this dependency issue.
