### ISSUE TITLE
server-wallet-profiling job flickers

### ISSUE THREAD

**Issue by geoknee** [statechannels/statechannels#2634]
https://app.circleci.com/pipelines/github/statechannels/statechannels/9222/workflows/4a194bd9-83fd-415d-b0d2-6d23d39fb705/jobs/44491

and

https://app.circleci.com/pipelines/github/statechannels/statechannels/9282/workflows/888bb2be-3d2b-4d75-a7f6-2346d6c29edc/jobs/44933

Possible cause #2619 ?

**Comment by geoknee** [comment]
https://app.circleci.com/pipelines/github/statechannels/statechannels/9372/workflows/fba85e95-795d-4311-bc13-598d9f24818b/jobs/45442

**Comment by geoknee** [comment]
Possibly relevant https://github.com/clinicjs/node-clinic-flame/issues/105

**Comment by geoknee** [comment]
This job has only an 81% success rate (others typically 94%+):

<img width="1178" alt="Screenshot 2020-10-20 at 11 52 35" src="https://user-images.githubusercontent.com/1833419/96577067-023ac880-12cb-11eb-9c9f-f6788a07574b.png">

**Comment by andrewgordstewart** [comment]
stale
