### ISSUE TITLE
server-wallet-stress-test-threaded job flickers

### ISSUE THREAD

**Issue by geoknee** [statechannels/statechannels#2658]
https://app.circleci.com/pipelines/github/statechannels/statechannels/9415/workflows/cc64d5e8-7568-49ba-8ad3-be126036c000/jobs/45724

**Comment by andrewgordstewart** [comment]
Is this the first instance you've seen? This looks worrying.

It looks like a possible memory bug in the `keccak` module.

I was previously unaware, but the [`keccak` module ](https://www.npmjs.com/package/keccak) seems to have bindings to native implementations in a nodejs environment:
> In browser pure JavaScript implementation will be used.

If we know which call lead to this (my guess is `getChannelId`) and we are worried about memory safety, we can use a rust implementation exposed with WASM bindings.

**Comment by geoknee** [comment]
It is the first instance I have seen, yes. I re-ran and it passed.

**Comment by andrewgordstewart** [comment]
I suspect it has nothing to do with threads, because it looks as if the main thread crashed with `SIGABORT`, probably during channel setup or something like that.

**Comment by andrewgordstewart** [comment]
This seems infrequent enough to close.

**Comment by geoknee** [comment]
https://app.circleci.com/pipelines/github/statechannels/statechannels/9999/workflows/9fcfdb73-d758-4d00-917e-4f6458e5898f/jobs/49063

**Comment by andrewgordstewart** [comment]
stale
