### ISSUE TITLE
Refactor `validateTransitionWithEVM` to be a pure function

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#2738]
Right. I guess the `validateTransition` has to fetch the bytecode (once) from the DB.

We could refactor it to accept the bytecode -- at that point it can be a pure function. The wallet could pass the bytecode to `updateChannel`

_Originally posted by @andrewgordstewart in https://github.com/statechannels/statechannels/pull/2737#discussion_r511189832_

**Comment by andrewgordstewart** [comment]
@snario thinks this is already done

**Comment by snario** [comment]
This was done in https://github.com/statechannels/statechannels/pull/2806
