### ISSUE TITLE
[server-wallet] Remove unnecessary "handlers" code

### ISSUE THREAD

**Issue by snario** [statechannels/statechannels#2803]
We're moving away from having "handlers" and closer towards [this architecture](https://www.notion.so/elfour/7bda6f3567e74734aa09883dd1945e65).

- [ ] If `UpdateChannelHandlerParams` is used, it should be re-named and re-exported elsewhere.
- [ ] `UpdateChannelError` should be re-exported elsewhere
- [ ] If `JoinChannelHandlerParams` is used, it should be re-named and re-exported elsewhere.
- [ ] `JoinChannelError` should be re-exported elsewhere

_Originally posted by @andrewgordstewart in https://github.com/statechannels/statechannels/pull/2795#discussion_r515651464_

**Comment by andrewgordstewart** [comment]
stale
