### ISSUE TITLE
Does the directly-funded-channel test work with Rinkeby contracts?

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#2872]

**Comment by andrewgordstewart** [comment]
@kerzhner This is done, right?

**Comment by kerzhner** [comment]
> @kerzhner This is done, right?

This is the outcome of the testing work.

**Comment by andrewgordstewart** [comment]
Ah, I was too quick reading the title, and thought in my head it said
" Test the chain service with Rinkeby contracts"

> > @kerzhner This is done, right?
> 
> This is the outcome of the testing work.

Does "The testing work" refer to something you're doing right now, or does it refer to testing on `sc-staging`?

**Comment by kerzhner** [comment]
Updated the title of the issue to be clearer. One follow up: https://github.com/statechannels/the-graph/issues/334
