### ISSUE TITLE
Create sane database names

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#2886]
I get this error because both server-wallet and the-graph are using the same generic "payer" DB name:
```
  ● payments › syncing › can update pre-existing channel, not send state, and sync later

    The migration directory is corrupt, the following files are missing: 20200707165856_initial.js, 20200712133135_nonces.js, 20200812081700_signing_wallet.js, 20200814010138_app_bytecode.js, 20200818083933_funding.js, 20200915140300_chain_service.js, 20201014174039_objectives.js, 20201014174040_ledger_requests.js, 20201014174041_ledgers.js, 20201027090000_chain_service_constraint.js, 20201027090001_channels_indexes.js, 20201029130000_transferred_out.js
```

We should not be using such generic names.

**Comment by andrewgordstewart** [comment]
**Observation**: This is similar to using environment variables such as `SERVER_DB_NAME` for the `server-wallet`'s database name. When used by a consumer of the library, it means they cannot use the same environment variable. (This has happened, with The Graph).

**Comment by lalexgap** [comment]
This has slightly been resolved by changes to the `server-wallet` codebase. We now use the following dbs: `server_wallet_receiver, server_wallet_payer, server_wallet_test`.

**Comment by andrewgordstewart** [comment]
`TEST_A` is still a bit weird. I could imagine someone having a db by that name on their system, and our test suite would destroy that data. (The data is most likely to not be important, but maybe we shouldn't be the judge of that?)
