### ISSUE TITLE
Ensure that channels don't get "stuck" if the chain service fails for some reason

### ISSUE THREAD

**Issue by snario** [statechannels/statechannels#2929]
Yesterday I had been using the `MockChainService` and `Direct` channels and saw several channels make request to be funded to the `MockChainService`. I realized later that I was using the `MockChainService`. So, I restarted the wallet and told it to use a real chain service. However, now, since the request to fund the channel was logged and stored in `Channel.chainServiceRequests` in the DB, it did _not_ try to ask for funding again to the (now real) chain service.

I think, in general, this is an issue. If the chain service fails for some reason and the wallet thinks that it successfully requested funding, then we are now in a spot where the wallet thinks that the channel will be funded and the chain service is doing nothing, and doesn't know it has to do anything.

What do we do about this?

**Comment by snario** [comment]
I think this relates to something I wrote earlier https://github.com/statechannels/statechannels/issues/2534. It seems like I initially expected `fundChannel` to be idempotent and that the wallet would not store information about whether or not it already called `fundChannel`.

**Comment by kerzhner** [comment]
> I think this relates to something I wrote earlier #2534. It seems like I initially expected `fundChannel` to be idempotent and that the wallet would not store information about whether or not it already called `fundChannel`.

Idempotency of `fundChannel` is probably a good property! Unfortunately, given the run loop architecture of the wallet, the wallet needs to store something to indicate that `fundChannel` is being attempted. Otherwise, the run loop will spin, continuously requesting the chain service to fund a channel over and over again.

An alternative is for wallet to await channel funding. Channel funding takes a long time (6 blocks), so that might not be a good idea.

**Comment by andrewgordstewart** [comment]
There could (should?) be some way for the channel manager to ask the wallet to re-try failed attempts.

**Comment by kerzhner** [comment]
Alternatively, the wallet can clear the chain request status after some time. The wallet can re-request `fundChannel` if holdings are not updated after a certain amount of time from the initial chain request.

However, this moves the wallet further away from being a reducer on top of a store. The wallet would now schedule tasks.

Perhaps the right place for this logic is either at the application level or some other cron-type system that calls the wallet.

**Comment by kerzhner** [comment]
Proposed strategy: https://www.notion.so/Chain-service-resilience-83c40060b2dc401e8e2efa6852b9c503

**Comment by snario** [comment]
The proposal is definitely an improvement over what we have now 👍 My main feedback would be that we could consider higher fidelity communication between the chain service and the wallet than "time elapsed since last call". For example, the chain service could identify and relay information like (a) transaction reverted, out of gas (b) transaction reverted: "thrown error from contract", (c) insufficient ETH to pay for transaction, or (d) unable to reach internet, API error, or (e) transaction pending. There could be some API on the chains service like `getStatusOnRequest(fingerprint)` which returns some information about the request.
