### ISSUE TITLE
Pass index to transfer (instead of destination)

### ISSUE THREAD

**Issue by geoknee** [statechannels/statechannels#2936]
Idea from @andrewgordstewart: Instead of passing in the `destination`, better to pass in the `index` of the destination in the allocation. Same goes (actually more urgently so) for `transfer`. 

We could even pass `indices: number[]` to target multiple destinations -- and have `[]` imply "all".

Because we pass in the abi-encoded allocation, this implies we know which destination is at which index (so no need to recheck this on chain).

_Originally posted by @geoknee in https://github.com/statechannels/statechannels/pull/2932#r527880096_

**Comment by geoknee** [comment]
If we go down this route it may be worth preserving the ordering of allocation items on chain: at present, items that have `amount: 0` are cleaned up and removed. This would make transaction ordering a real concern.

**Comment by andrewgordstewart** [comment]
In that case, it's already a concern isn't it? In case we call transfer with one item, are you saying it will currently remove that item from the outcome?

**Comment by geoknee** [comment]
It will remove that item if the amount is zero, yes. 

Given that, there is slightly more work to do in the wallet if we go down the "index" route. I think in either case you need to know the exact outcome on chain that you want your `transfer` to run against, otherwise it will fail. With indices and "outcome garbage collection", clients need to recompute the index, say if they need to retry because someone just `transfer`ed and the outcome on chain changed. With "destinations" and "outcome garbage collection", you still need to track an up-to-date outcome but don't need to recompute the index that points to the destination you want.

**Comment by andrewgordstewart** [comment]
I don't think there's a significant benefit to removing `0`-amount items, right? Was it that it seemed like like a "clean" thing to do?

**Comment by andrewgordstewart** [comment]
Observing that all solutions will require the wallet to track changes to the registered outcome

There are alternative APIs, such as:
```
    function _transfer(
        bytes32 fromChannelId,
        bytes memory allocationBytes,
        bytes32[] memory destinations,
        uint256 maxTransfers
    )
```

where the behaviour of `_transfer` skips `0`-amount items.
