### ISSUE TITLE
ChainService does not manage transaction nonces correctly

### ISSUE THREAD

**Issue by snario** [statechannels/statechannels#2986]
It appears to be the case that the `ChainService` does not manage nonces correctly. ~`fundChannel` will be called in separate processes and thus `ethers` internal nonce management won't work, and we see errors like this pop up:~

```
(node:84130) UnhandledPromiseRejectionWarning: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":62,\"error\":{\"code\":-32000,\"message\":\"already known\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf8aa8219c6843b9aca0082b09c9431958e219073d60fdceb1d608c293754331dd35280b84439509351000000000000000000000000e2b30b251e74bf33e5d8f795b576292c135e8a8900000000000000000000000000000000000000000052b7d2dcc80cd2e40000002ca0399110542c3c566caaae6e8d5f88eb029d227a1b845c31695413fb9d4835c318a03d8b7a603d664f0ef0439295b1a18d5f62bb1b06d3107ddd5cf7877b579d575b\"],\"id\":62,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://rinkeby.infura.io/v3/<REDACTED>", code=SERVER_ERROR, version=web/5.0.7)
    at Logger.makeError (/Users/liam/Documents/Projects/statechannels/thegraph-project/gateway/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/Users/liam/Documents/Projects/statechannels/thegraph-project/gateway/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at /Users/liam/Documents/Projects/statechannels/thegraph-project/gateway/node_modules/@ethersproject/web/lib/index.js:264:32
    at step (/Users/liam/Documents/Projects/statechannels/thegraph-project/gateway/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/Users/liam/Documents/Projects/statechannels/thegraph-project/gateway/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/Users/liam/Documents/Projects/statechannels/thegraph-project/gateway/node_modules/@ethersproject/web/lib/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Related to #2929

**Comment by andrewgordstewart** [comment]
Let's be clear in this case: are there really multiple processes calling fundChannel? Or are there just multiple threads? If it's the former, what are the processes?

**Comment by snario** [comment]
I just tested with one process and one one thread and I still see the bug actually. I'm not 100% what the root cause is. The situation is that the `ChainService` is definitely being sent ~20 calls to `fundChannel` concurrently for the same asset holder on Rinkeby.

**Comment by andrewgordstewart** [comment]
What were the initial conditions that lead to this behaviour? Can you describe a "reproduction scenario"?

**Comment by snario** [comment]
It looks like at one point I ran the `ChainService` with 20 concurrent calls to `fundChannel` and let it wait for some time. Some of the transactions hit the original error "already known"; presumably due to [`getTransactionCount("pending")` ](https://github.com/ethers-io/ethers.js/blob/e805ab5b2d9bac400babf42ae1a84ba47f136253/packages/experimental/src.ts/nonce-manager.ts#L37) not returning correctly...? Anyway, this led to an enormous number of "pending" transactions. Then, I restarted the process which triggered several more transactions to be submitted; most of which hit this "replacement transaction underpriced" error. It was very confusing as none of these pending transactions showed up on Etherscan until 30 minutes later: https://rinkeby.etherscan.io/address/0x5e0e63051d658480f40c4211133d620b41e9cebd.

**Comment by snario** [comment]
On another run, with just one channel, one thread, and one process, I see `Error: nonce too low` which `ethers` re-throws as `Error: nonce has already been used`

**Comment by andrewgordstewart** [comment]
Is the private key being used only used in a single environment?

**Comment by snario** [comment]
It appears actually that the same mnemonic was periodically being used on a Kubernetes pod to call `approve`.

I think it's reasonable to expect that a transaction might be happening at the same time for some other purpose for an ethereum address that is passed in to the `ChainService`, and so it should be able to be resilient to that case. Or, perhaps a warning should be thrown?

**Comment by andrewgordstewart** [comment]
It has long been specifically said, at least verbally, that we assume that the private key provided to the SC wallet is specifically for use in the SC wallet.

I don't know how you can provide a warning in case the user decides to reuse a private key for the SC wallet?

**Comment by snario** [comment]
Currently in production it is not the case that the private key provided to the SC wallet is specifically used for the SC wallet. We can open an issue for that.

**Comment by andrewgordstewart** [comment]
Yeah, we either do that, or we tighten the chain service to be robust to this environment.

**Comment by andrewgordstewart** [comment]
> It appears actually that the same mnemonic was periodically being used on a Kubernetes pod to call `approve`.

Can you clarify this point? Are you saying there is a `chain-service` running in a k8s pod that is periodically calling `approve`? Or is the k8s pod using the same private key for multiple purposes?

**Comment by snario** [comment]
`gateway` calls `approve` on startup

**Comment by andrewgordstewart** [comment]
Action to take: Request from The Graph that we be provided a private key dedicated for SC management. If they object to that, we'll learn why it's a bad idea and get guidance from them about the right solution to this problem.

**Comment by andrewgordstewart** [comment]
> `gateway` calls `approve` on startup

Do you mean the gateway manager? Why it call approve on startup?

**Comment by snario** [comment]
Yes — it did so to call `collect` previously. Probably can be removed

**Comment by andrewgordstewart** [comment]
Unless we get clear evidence that the _chain service_ is not managing nonces correctly, I'd consider this a non-issue.
