### ISSUE TITLE
ChainService unnecessarily manages asset holder's token allowance

### ISSUE THREAD

**Issue by snario** [statechannels/statechannels#2987]
Right now, every deposit a chain service makes for a token makes an additional call to `increaseAllowance`. This seems to unnecessarily add an additional layer of complexity and fees for the user of the wallet.

I argue we should simply `approve` `MaxUint256` once and ignore allowance management. Since asset holders are (1) audited and (2) callable with arbitrary arguments (e.g., `increaseAllowance` could be called with `MaxUint256`) anyway, I don't think the additional overhead of managing allowances is adding any security benefits

Related to #2929

**Comment by kerzhner** [comment]
The chain service has the following option: https://github.com/statechannels/statechannels/blob/master/packages/server-wallet/src/chain-service/chain-service.ts#L54. I gather that this is not sufficient. Can you explain why?

**Comment by snario** [comment]
That option is unused. Maybe you could rename this to "Server wallet unnecessarily manages the asset holder's token allowance" and we should make the server wallet propagate that option all the way up to the config of the server wallet.

**Comment by andrewgordstewart** [comment]
>  Since asset holders are (1) audited

In general, asset holders are not audited. A general wallet might be asked to use many different asset holders. Nevertheless, it probably makes sense to trust asset holders _in the short term_ and push secure allowance management down the line.

**Comment by andrewgordstewart** [comment]
Fixed by  #2994
