### ISSUE TITLE
ChainService allowanceAlreadyIncreased argument is unused

### ISSUE THREAD

**Issue by snario** [statechannels/statechannels#2988]
Right now if `increaseAllowance` is called, and then the process crashes or restarts before a `deposit` it sent to chain, then `increaseAllowance` will be called a second time. This might not be relevant if we change behaviour e.g., #2987 but right now it is an issue as it can take several minutes for a  transaction to be mined.

**Comment by snario** [comment]
Related to #2929

**Comment by kerzhner** [comment]
To be honest, I am pretty confused about what this issue is.

Regardless of my confusion, perhaps https://github.com/statechannels/statechannels/pull/2994 addresses the concerns?
