### ISSUE TITLE
Concluding 20k channels blocks the main nodejs thread for hours

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3000]
> [Jannis] `mergeProp` concatenates old objectives and one new objective and then does `uniqueWith` using a deep comparison to ensure the result of the concatenation is still unique values. It should be enough to just check if the new objective isn’t already included.

There isn't necessarily an argument for concluding 20k channels at once. However, there is still a `O(n^2)` (?) algorithm running in the main thread of the gateway manager when closing (and opening?) channels.

**Comment by tomclose** [comment]
https://github.com/statechannels/the-graph/pull/442#issuecomment-737063311
