### ISSUE TITLE
test output is too long

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3068]
https://app.circleci.com/pipelines/github/statechannels/statechannels/11009/workflows/9885820f-7d33-4238-ace2-7e9466281db9/jobs/53817/parallel-runs/0/steps/0-106

```
Your output is too large to display in the browser.

Only the last 400000 characters are displayed.
```

**Comment by lalexgap** [comment]
This has been resolved ( probably due to someone cleaning up some `console.log` statements). See [here](https://app.circleci.com/pipelines/github/statechannels/statechannels/12055/workflows/290de48d-2e64-4a7d-9ca9-2724f5ee14ac/jobs/58772) for an example.

**Comment by lalexgap** [comment]
This has been resolved ( probably due to someone cleaning up some `console.log` statements). See [here](https://app.circleci.com/pipelines/github/statechannels/statechannels/12055/workflows/290de48d-2e64-4a7d-9ca9-2724f5ee14ac/jobs/58772) for an example.

**Comment by lalexgap** [comment]
This has been resolved ( probably due to someone cleaning up some `console.log` statements). See [here](https://app.circleci.com/pipelines/github/statechannels/statechannels/12055/workflows/290de48d-2e64-4a7d-9ca9-2724f5ee14ac/jobs/58772) for an example.
