### ISSUE TITLE
EnsureObjective always returns a status of pending

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#3122]
Currently if an objective already exists we will return a status of `pending` for it even if the existing objective has a different status.

_Originally posted by @lalexgap in https://github.com/statechannels/statechannels/pull/3121#discussion_r554099702_

**Comment by lalexgap** [comment]
I think the solution is to create a `insertOrFetch` method that `ensureObjective` can use

**Comment by geoknee** [comment]
via #3259
