### ISSUE TITLE
Canonical defund channel protocol

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3124]
See discussion [here](https://www.notion.so/Jan-11-Close-channel-protocol-4a167972a7264e1ebbb594c4624c152b#0e9cf1069c4a4317b7ed0a490d6ebd62)

Certain protocols share defunding logic. At the moment `CloseChannel` and `DefundChannel` protocols defund a channel. In the future, `ChallengeChannel` will replace `DefundChannel`. We can create a new `Defunder` protocol that unifies defunding logic for any type of channel (regardless of how a channel is funded).

Some of the functionality of the `Defunder` protocol is:
- When the channel is ledger-funded, create a LedgerDefund request
- When we have a conclusion proof and the channel is directly funded, submit a `ConcludeAndWithdraw` transaction.

Once the `Defunder` protocol exists, `CloseChannel`'s responsibility will become:
- Make sure the channel is finalizable, by exchanging a conclusion proof
- Then, trigger a `Defunder` protocol.

**Comment by wunnaii** [comment]
note: Liam would like to chat/discuss this topic if needed (per sprint planning session).
