### ISSUE TITLE
Does `crankUntilIdle` crank until idle?

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3142]
Myself and @wunnaii  were looking through the wallet code yesterday, and noticed that `crankUntilIdle`
1. fetches a list of objectives: [link](https://github.com/statechannels/statechannels/blob/1e6a5109a768df25b836faff62ec03d2378fb9fd/packages/server-wallet/src/wallet/wallet.ts#L689-L691)
2. iterates through those objectives, removing them once they're "cranked" once: [link](https://github.com/statechannels/statechannels/blob/1e6a5109a768df25b836faff62ec03d2378fb9fd/packages/server-wallet/src/wallet/wallet.ts#L694)

Is there a test case for the following edge case?
1. The participants of a directly funded channel are `[alice, bob]`
2. The initial outcome is `{bob: 20}`

It seems to me like what might happen is:
1. Alice sends the objective & the 1st state to Bob
2. Bob approves the objective, "cranking" once and signing the 1st state
3. Bob _does not crank again_, and therefore does not submit a deposit

**Comment by tomclose** [comment]
The way that the protocols are now written means that one crank is always enough (see [here](https://github.com/statechannels/statechannels/blob/1e6a5109a768df25b836faff62ec03d2378fb9fd/packages/server-wallet/src/protocols/channel-opener.ts#L42-L55) for the open channel code relevant to your example). Coupled with the understanding that each channel is only touched by one objective at at time, this means that it is enough to go through the list once (between each round of updating ledgers).

There's a test for almost that scenario [here](https://github.com/statechannels/statechannels/blob/1e6a5109a768df25b836faff62ec03d2378fb9fd/packages/server-wallet/src/protocols/__test__/open-channel.test.ts#L40-L43).

It's possible that `crankUntilIdle` is no-longer an appropriate name for that function...

**Comment by tomclose** [comment]
To answer the question, I guess technically it does, as an objective is always idle after a single crank.

**Comment by andrewgordstewart** [comment]
> The way that the protocols are now written means that one crank is always enough (see [here](https://github.com/statechannels/statechannels/blob/1e6a5109a768df25b836faff62ec03d2378fb9fd/packages/server-wallet/src/protocols/channel-opener.ts#L42-L55) for the open channel code relevant to your example). Coupled with the understanding that each channel is only touched by one objective at at time, this means that it is enough to go through the list once (between each round of updating ledgers).
> 
> There's a test for almost that scenario [here](https://github.com/statechannels/statechannels/blob/1e6a5109a768df25b836faff62ec03d2378fb9fd/packages/server-wallet/src/protocols/__test__/open-channel.test.ts#L40-L43).

:+1:

> It's possible that `crankUntilIdle` is no-longer an appropriate name for that function...

Hm yeah, it doesn't seem quite right anymore.
