### ISSUE TITLE
ObjectiveModel should handle OnConflict internally

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#3150]
I think the `ObjectiveModel` should handle this logic? Right now, the internal model implementation has leaked into the store.

Postgres allows `ON CONFLICT`, so the `ObjectiveModel` can do, for instance,
```
INSERT foo
ON CONFLICT (name of uniqueness constraint) DO NOTHING
```

_Originally posted by @andrewgordstewart in https://github.com/statechannels/statechannels/pull/3133#discussion_r557714161_

**Comment by geoknee** [comment]
Via #3315
