### ISSUE TITLE
Wallet database initialization

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#3174]
# Current flow
There is a one-to-one mapping between a server wallet and a database. For a wallet to be functional:
1. A database must be created either via `createdb` (or another manual way) or via using the wallet [DBAdmin class ](https://github.com/statechannels/statechannels/blob/master/packages/server-wallet/src/db-admin/db-admin.ts#L1)
1. The database must be migrated via `knex migrate` or using DBAdmin.

If DBAdmin class is used, the sequence of events is:
1. The wallet is instantiated using [`create`](https://github.com/statechannels/statechannels/blob/master/packages/server-wallet/src/wallet/index.ts#L8).
1. DBAdmin either migrates the DB or creates + migrates the DB.

# Problem statement
[Recent changes](https://github.com/statechannels/statechannels/blob/master/packages/server-wallet/src/wallet/wallet.ts#L106) part of https://github.com/statechannels/statechannels/pull/3148 require that that a database is created and migrated before the wallet is created.

# Another concern
Our unit test did not fail when this issue was introduced. Some test print out error messages. But the error is thrown in an asynchronous callback, [so the error does not result in a test failure](https://app.circleci.com/pipelines/github/statechannels/statechannels/11454/workflows/b013c72c-b0fb-4391-b3d7-1f754220e577/jobs/55903). Curiously, the tests do fail for Mike locally.

# Proposed solutions
1. DBAdmin is extracted from the wallet and is always used to create and migrate the database before a wallet is created.

# Nice to haves
It may also be worthwhile to check database connectivity when the wallet is created. It would be nicer for the wallet to fail definitely then happening to fail the first time we actually check against the database.

**Comment by lalexgap** [comment]
This will also require updating the `the-graph` repo to no longer `wallet. DBAdmin()`.
