### ISSUE TITLE
Issue labels

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3177]
Recorded for posterity

```
💣 BREAKING CHANGE (#e57147) - fix or feature that would cause existing functionality to not work as expected
✨ enhancement     (#a2eeef) - change which adds new functionality
🐛 bug             (#d73a4a) - non-breaking change which fixes an issue
🧹  chore          (#bdc2b6) - tech debt, improved developer experience, etc
🐎  performance    (#3033F4) - either gas efficiency or computational efficiency
📖  documentation  (#0075ca) - Improvements or additions to documentation
🔒 security        (#191708) - requires two sets of eyes before merging
```

**Comment by geoknee** [comment]
@andrewgordstewart the way things are setup, we are getting a new mention for this issue on every new PR :-/

**Comment by geoknee** [comment]
@andrewgordstewart the way things are setup, we are getting a new mention for this issue on every new PR :-/

**Comment by andrewgordstewart** [comment]
Let's find a more appropriate place to store this info. I put it in an info in a slight rush...

**Comment by wunnaii** [comment]
Documented in notion https://www.notion.so/Team-working-agreements-2a95c926bb5642e5a5c42e4b74a9dd24#b304e56734a74dfbb341b8b4b27b1c0c
