### ISSUE TITLE
e2e graph-payment tests verify that channels are closed and defunded?

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#3207]

**Comment by kerzhner** [comment]
1. If not, write the test.
2. Verify that the test passes for the current logic of gateway and indexer racing to submit the withdraw transaction.
3. Use the test to evaluate the success of https://app.zenhub.com/workspaces/state-channels-5ff743783009980020a72feb/issues/statechannels/project-management/39

**Comment by wunnaii** [comment]
@kerzhner can you leave a comment

**Comment by lalexgap** [comment]
I think this can be closed but would like @kerzhner to verify.
