### ISSUE TITLE
Flickering ledger funding unit tests

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#3208]
Examples:
- https://app.circleci.com/pipelines/github/statechannels/statechannels/11557/workflows/c675149d-664f-411e-82f4-4a30a589f121/jobs/56375
- https://app.circleci.com/pipelines/github/statechannels/statechannels/11565/workflows/58a3c379-030c-45a6-9253-51cab0ff9edc/jobs/56411

**Comment by geoknee** [comment]
https://app.circleci.com/pipelines/github/statechannels/statechannels/11630/workflows/dcb18a06-39c9-49e9-a4d2-e00b9097df92/jobs/56707

**Comment by wunnaii** [comment]
5s timeout on unit test is may be causing it to fail?

**Comment by wunnaii** [comment]
This issue does not seem to occur anymore
