### ISSUE TITLE
Wallet e2e test occasionally fails when using ganache

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#3213]
**Describe the bug**
If we attempt to run the e2e test using a ganache instance the wallet occasionally crashes with a DB error when the holdingUpdated event fires and we haven't received any states yet.

The problem is that `holdingsUpdated` event fires from the chain before the receiver has received the first state. Since the receiver hasn't received the first state there is no channel entry for it. This means the attempt to insert into the `Funding` table fails due to a foreign key reference to the channels table.

**To Reproduce**
1.  Usin[g this branch ](https://github.com/statechannels/statechannels/pull/3202/commits/0e5adcb4ec8a60ce512a8c56bdb42110eb021fe4)
1. Run the e2e test.
2. Notice that the test fails.

**Expected behavior**
The wallet should handle the case of being alerted to a deposit before it has received a state.

**Logs**
```
    ForeignKeyViolationError: insert into "funding" ("amount", "asset_holder", "channel_id", "transferred_out") values ($1, $2, $3, $4) returning "channel_id", "asset_holder" - insert or update on table "funding" violates foreign key constraint "funding_channel_id_foreign"

      at wrapError (../../node_modules/db-errors/lib/dbErrors.js:19:14)
      at handleExecuteError (../../node_modules/objection/lib/queryBuilder/QueryBuilder.js:1506:32)
      at QueryBuilder.execute (../../node_modules/objection/lib/queryBuilder/QueryBuilder.js:687:20)
          at runMicrotasks (<anonymous>)
```

**Comment by andrewgordstewart** [comment]
Might be resolved?

**Comment by lalexgap** [comment]
I think this was actually a local artifact of introducing a new E2E test.

Since both tests could run at the same time `registerExistingChannels` would pick up channels from the other tests causing this failure. Using `--runInBand` resolved this.
