### ISSUE TITLE
Wallet challenge function should accept an array of Signed States

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#3215]
**Describe the bug**
Currently, the challenge function on the wallet only accepts a single `State`.  The wallet then signs this and calls `challenge` on-chain with it. 

This isn't enough for a valid challenge proof as we need to provide a **supported** state.  To support this we should just update the challenge API to accept a collection of `SignedState`s.

**Comment by andrewgordstewart** [comment]
I think this is a "Nice to have" for v0, where we can assume that we are given a single, fully supported state

**Comment by lalexgap** [comment]
Closing as superseded by another issue in a different repo
