### ISSUE TITLE
Think about challenge idempotency

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#3218]
We should assume that a channel manager might restart sometime after `removeAllocations` is called and before a challenged channel is defunded. What happens with a restart? Is the entire challenge flow idempotent?

**Comment by andrewgordstewart** [comment]
💡 :
1. `challenge` returns an objective with an id
2. the channel manager stores the ids for running challenge objectives.

There is still the edge case that the CM crashes just between 1 & 2, but that is a much smaller edge case to control.

**Comment by kerzhner** [comment]
https://www.notion.so/Initial-Challenging-Implementation-Challenging-V0-d370aaaa890d4e91ba915cf92a28e7b2#14451c3fd38c4f66930aa94cc000086a for the discussion.

**Comment by andrewgordstewart** [comment]
> https://www.notion.so/Initial-Challenging-Implementation-Challenging-V0-d370aaaa890d4e91ba915cf92a28e7b2#14451c3fd38c4f66930aa94cc000086a for the discussion.

Is there an obvious solution to you, assuming that we had first class objectives?

I spent 5 minutes [sketching this out](https://www.notion.so/Initial-Challenging-Implementation-Challenging-V0-d370aaaa890d4e91ba915cf92a28e7b2#2e59373d00eb40f6b9de5e9cd09b4dc2).

**Comment by lalexgap** [comment]
Closing this and we can respec out challenging when we want it.

**Comment by lalexgap** [comment]
Closing this and we can respec out challenging when we want it.

**Comment by lalexgap** [comment]
Closing this and we can respec out challenging when we want it.
