### ISSUE TITLE
There is no mechanism for syncing objectives

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3224]
**Describe the bug**
If `payer` calls `wallet.createChannel`, this generates an objective in the resulting `response`.

If this outgoing message is dropped, the wallet offers no mechanism to inform the peer of the objective.

**To Reproduce**
Run an e2e test in `graph-payments` with `dropOutgoingRate` set to 0.5. This is random, so you may need to re-run it.

**Expected behavior**
either
- `syncChannels` should also sync ongoing objectives
- there should be a `syncObjective` API

**Comment by wunnaii** [comment]
Note: changes are limited to statechannels repo only. Refer to #[33](https://github.com/statechannels/graph-payments/issues/33) for the change required in graph payments repo
