### ISSUE TITLE
ensureObjective locks the channelId for the objective

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3226]
Currently, `store.ensureObjective` does not lock a channel. But, eg., the `CloseChannelObjective.commence` calls `store.lockApp` with a `channelId`.

Since every objective has a canonical `target_channnel_id`, `store.ensureObjective` can itself lock the channel itself.

**Comment by wunnaii** [comment]
@geoknee is this ready to be deleted?

**Comment by geoknee** [comment]
As far as I can tell, there is currently no `ensureObjective` method on the store. I think that's enough to close this issue.
