### ISSUE TITLE
Objectives track times

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3230]
# Why: Problem description :confused:
- A channel manager (CM) aware of "Operations" would want to know about long-running operations.
- An app using a CM may wish to monitor statistics about how long operations take

# What: Describe the solution you'd like :sparkles:  
1. Objectives should have a `created_at` and an `updated_at` column.
2. `updated_at` should be set to `now()` when the objective is updated at

## Open question
What should happen when a child objective is updated?

**Additional context**
- [Objective stalls due to an incorrect protocol design](https://www.notion.so/First-class-objectives-402f747da81b4bf38de1a3f28dd6ca31#c6deeaa3fb504875bbe023d7bd097b81)
- [Objective stalls due to a network error](https://www.notion.so/First-class-objectives-402f747da81b4bf38de1a3f28dd6ca31#b2d0ca76b807453e8f0d8017f6f8647a)

**Comment by wunnaii** [comment]
Do not start this ticket if #[3225 ](https://github.com/statechannels/statechannels/issues/3225) is in progress

**Comment by geoknee** [comment]
Thoughts from standup 4th Feb:

`createdAt` could be `lastCrankedAt` or `progressLastMadeAt`, depending on what we deem important to store. Then, we may need to think more carefully about how to detect those events.

**Comment by geoknee** [comment]
The API types should be updated to include 
- the timestamps
- the objective id
- *not* the status (this will be clear from context, e.g. the name of the event fired when an objective completes)
