### ISSUE TITLE
nested objectives should be synced with their parent

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3234]
# Why: Problem description :confused:
Suppose a channel manager (CM) calls `concludeLedgerAndFundedChannels`, getting an operation `o1`, and crashes shortly after.

When the CM restarts, it would want to sync `o1`. But `o1`'s objective may have child objectives.

# What: Describe the solution you'd like :sparkles:  
When an objective is synced, so are its incomplete children.

**Comment by geoknee** [comment]
Closing because it depends on a closed ticket #3227

**Comment by geoknee** [comment]
Closing because it depends on a closed ticket #3227

**Comment by geoknee** [comment]
Closing because it depends on a closed ticket #3227
