### ISSUE TITLE
`yarn test:e2e` does not run

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3240]
**Describe the bug**
When I run `yarn test:e2e` in the `server-wallet` package, I see
```
(node:67401) UnhandledPromiseRejectionWarning: DBError: select "channels".* from "channels" - relation "channels" does not exist
```

**To Reproduce**
```
❯ dropdb server_wallet_payer;
❯ dropdb server_wallet_receiver;
```
Then, follow the instructions in the [readme](https://github.com/statechannels/statechannels/tree/master/packages/server-wallet)
```
❯ yarn test:e2e;
```

**Expected behavior**
To run the e2e test, we need to
1. create & migrate `server_wallet_payer`
2. create & migrate `server_wallet_receiver`

Either
A. the readme should instruct a developer to do 1 & 2
B. the e2e test itself should do 1 & 2
C. there should be a `run_e2e.sh` script which does 1 ^ 2, similar to [this](https://github.com/statechannels/graph-payments/blob/main/packages/e2e-testing/scripts/run-local.sh)

**Additional context**

The instructions [here](https://github.com/statechannels/statechannels/blob/master/packages/server-wallet/e2e-test/README.md#running-locally) are out of date, and are not referenced in either the root readme or the `server-wallet` readme.

**Comment by isoosiss7** [comment]
I can fix this, assigned to myself

**Comment by isoosiss7** [comment]
Pls review: https://github.com/statechannels/statechannels/pull/3258

**Comment by andrewgordstewart** [comment]
Fixed by https://github.com/statechannels/statechannels/pull/3258
