### ISSUE TITLE
`channels.vars` should not store channel constants

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3241]
**Describe the bug**
The `vars` column should be an array of [`SignedStateVarsWithHash`](https://github.com/statechannels/statechannels/blob/a79b3a58b9e0204c67d0ee1b51a5602a1b3262e9/packages/wallet-core/src/types.ts#L89) JSON blobs. In practice, the array elements store channel constants, among other fields.

**To Reproduce**

First, remove the `afterAll` function from `ledger-manager.test.ts`:
<img width="923" alt="Screen Shot 2021-02-01 at 7 37 49 PM" src="https://user-images.githubusercontent.com/8432675/106544581-0333e680-64c5-11eb-8992-e4b05f888fc3.png">

This means you can deterministically run this test, and observe the data stored in the database after the test run.

Then, CD into the `server-wallet` package, and run

```
> yarn test ledger-manager -t 'generates signed ledger update when proposals were not identical but overlapped'
```

Now, you should have some channels where the `vars` column containing non-variables.
```
> psql server_wallet_payer -c 'select vars->0 from channels limit 1;'
```

After my test run, for instance, one `var -> 0` entry (piped through `jq`) looks like
```
❯ pbpaste | jq                                                    
{
  "appData": "0x",
  "chainId": "0x01",
  "isFinal": false,
  "outcome": {
    "type": "SimpleAllocation",
    "allocationItems": [
      {
        "amount": "0x01",
        "destination": "0x00000000000000000000000000000000000000000000000000000000000AaAa1"
      },
      {
        "amount": "0x00",
        "destination": "0x00000000000000000000000000000000000000000000000000000000000BbBB2"
      }
    ],
    "assetHolderAddress": "0x0000000000000000000000000000000000000000"
  },
  "turnNum": 0,
  "channelId": "0x3dc8e97155e1d74f9ba973780ced196d0d0974a2c387e20db58871b39641a136",
  "stateHash": "0x913ca5312745cecc8aa22d84c23d67aa6873294afb804b7e1b1e777de915bd73",
  "signatures": [
    {
      "signer": "0x11115FAf6f1BF263e81956F0Cc68aEc8426607cf",
      "signature": "0xe10890c9be256b68962d46b2771775eb2bb9a6222cd52ba1541667e2e89a1c8d7bde62a760d0a756d0b815d154ae445431b5f868e5e1d4a7d93204881a6e04551c"
    },
    {
      "signer": "0x2222E21c8019b14dA16235319D34b5Dd83E644A9",
      "signature": "0xf53614a23290b7e84a9df0769c82592681bc72333b5ccf86c01b176cbc5163fb16a60ab5910f586e808fe08da9957b1ee06e12af4432bc3d295f24f5d0b8c01e1b"
    }
  ],
  "channelNonce": 2,
  "participants": [
    {
      "destination": "0x00000000000000000000000000000000000000000000000000000000000AaAa1",
      "participantId": "alice",
      "signingAddress": "0x11115FAf6f1BF263e81956F0Cc68aEc8426607cf"
    },
    {
      "destination": "0x00000000000000000000000000000000000000000000000000000000000BbBB2",
      "participantId": "bob",
      "signingAddress": "0x2222E21c8019b14dA16235319D34b5Dd83E644A9"
    }
  ],
  "appDefinition": "0x000000000000000000000000000000000000ADef",
  "challengeDuration": 9001
}
```

**Expected behavior**
Each element of the `vars` array should only contain elements of this type
```
{
  outcome: Outcome;
  turnNum: number;
  appData: string;
  isFinal: boolean;
  stateHash: string;
  signatures: {signature: string; signer: Address}[];
}
```

**Additional context**

I think that state vars are added in two places:
1. [`addMyState`](https://github.com/statechannels/statechannels/blob/a79b3a58b9e0204c67d0ee1b51a5602a1b3262e9/packages/server-wallet/src/wallet/store.ts#L201)
2. [`addSignedState`](https://github.com/statechannels/statechannels/blob/a79b3a58b9e0204c67d0ee1b51a5602a1b3262e9/packages/server-wallet/src/wallet/store.ts#L636)

**Comment by isoosiss7** [comment]
@andrewgordstewart
Thanks for such detailed explanation, I have a PR ready for review:
https://github.com/statechannels/statechannels/pull/3255

**Comment by isoosiss7** [comment]
Ooops, some tests were broken by this.  Will look tomorrow.

**Comment by andrewgordstewart** [comment]
Yep. I think the tests are probably incorrect in this case, let me check for sure.
