### ISSUE TITLE
Events are not emitted by MultiThreadedWallet

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3262]
**Describe the bug**
The `MultiThreadedWallet` extends the `SingleThreadedWallet`, which extends `EventEmitter`. However, events emitted by worker threads are not emitted by the main thread, meaning that consumers of a `MultiThreadedWallet` cannot listen to them.

**To Reproduce**
The [stress test](https://app.circleci.com/pipelines/github/statechannels/graph-payments/98/workflows/46d12aa4-472e-460a-adcc-3571f4f21a57/jobs/652) fails on https://github.com/statechannels/graph-payments/commit/a6e6f009957e2df46226683f0c342124409013d5.

**Expected behavior**
The `MultiThreadedWallet` should have the same API implementation as the `SingleThreadedWallet` API.

**Comment by wunnaii** [comment]
i tagged this to First class objectives epic, please fix if it's wrong
