### ISSUE TITLE
Group test using peer wallets

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#3279]
Wallet tests are grouped by the setup and teardown configuration required for the test. The groupings are:
- unit tests configured via `jest.config.js`
- tests that use the ganache chain configured via `jest.chain.config.js`
- e2e tests that spin up application servers configured via `jest.e2e.config.js`
- stress tests that test the performance of the wallet configured via `jest.stress.config.js`

There seems to be another class of tests that uses 2 wallets to test the interaction between the wallets. An example is https://github.com/statechannels/statechannels/blob/20e8101cd3d78ff808f699d497e6835444b0c62a/packages/server-wallet/src/__test__/sync-objectives.test.ts#L27

For this class of tests:
- [x] Common setup and teardown can be factored out into `jest.with-peers.config.js`
- [x] Tests that use this setup and teardown can be grouped under a directory like `__test__/with-peers/...`
- [x] A debug configuration can be added to `packages/server-wallet/.vscode/launch.json`

**Comment by andrewgordstewart** [comment]
https://github.com/statechannels/statechannels/pull/3275#discussion_r574237745

> nit: this file ought to be called something a bit different -- otherwise, it's not obvious why it's separate from the test file included below.

> I think there's a set of tests which play two wallets against each other. Perhaps they should be grouped under __test__/with-peers/... or something like that.

**Comment by NiloCK** [comment]
@lalexgap The test files that are affected by this refactor are already grouped by different folder hierarchies (eg, `/__test__/create-and-close-channel`, `/__test__/crash-tolerance`). Moving them all to `/__test__/with-peers/` would lose the previous logical grouping.

Any comment on whether it's better to leave them in their current physical location? I could leave them as-is and still create a `.config.js` and add a specific `test:with-peers' testing script.

**Comment by andrewgordstewart** [comment]
I _think_ that every test in [`src/__test__`](https://github.com/statechannels/statechannels/tree/master/packages/server-wallet/src/__test__) is a "test with peer". So, it might be as easy as
1. creating `with-peers` as a subdirectory of `src/__test__`
2. Moving the relevant contents of `src/__test__` to `src/__test__/with-peers`

This leaves the option to have, eg,
- `src/__test__/integration/...`
- `src/__test__/stress/...`
to logically organize different subsets of "top-level" tests
