### ISSUE TITLE
Add tests for schema migration

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#3307]
Outside the scope of this PR, but at some point we might want to automate testing of the schema migrations against existing data at some point.

_Originally posted by @lalexgap in https://github.com/statechannels/statechannels/pull/3286#discussion_r577043983_

**Comment by geoknee** [comment]
Possible duplicate of https://github.com/statechannels/project-management/issues/55 ?

**Comment by lalexgap** [comment]
> Possible duplicate of [statechannels/project-management#55](https://github.com/statechannels/project-management/issues/55) ?

Oops, looks like. Closing.
