### ISSUE TITLE
We only check the chain id when challenging/conclude/etc 

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#3323]
**Describe the bug**
Currently, there's only one check on the `chainId`, and it occurs in the [contract](https://github.com/statechannels/statechannels/blob/master/packages/nitro-protocol/contracts/ForceMove.sol#L916:L916) when it computes a channelId. 

I think there are two changes here:
- The `wallet` should probably check the `chainId` on incoming channels against the chainId the `wallet` knows about
-  A `require` statement could be added to `_requireValidProtocolTransition` on the contract to check the chain id.

**Comment by lalexgap** [comment]
> * A `require` statement could be added to `_requireValidProtocolTransition` on the contract to check the chain id.

@geoknee does that sound reasonable?

**Comment by lalexgap** [comment]
> > * A `require` statement could be added to `_requireValidProtocolTransition` on the contract to check the chain id.
> 
> @geoknee does that sound reasonable?

The main reason I want to add to that is so the javascript check can mirror the solidity code. Perhaps that's overkill and a simple sanity check in the `wallet` is enough.

**Comment by geoknee** [comment]
@lalexgap I had quite a long think about this and my preferred solution is here statechannels/statechannels#3324
