### ISSUE TITLE
Sketch out approach for Browser Wallet? RFC

### ISSUE THREAD

**Issue by wunnaii** [statechannels/statechannels#3354]
# Why: Problem description :grey_question:
Refer to [notion doc](https://www.notion.so/Browser-wallet-29f164c7ff6b4fcfb1e0fad91237ee02)

# What: Describe what a solution should resolve :grey_exclamation:  
* Create an RFC with the proposed definition of wallet types and interfaces. 
* Consider interoperability with server and browser wallet

* Let #sc-general-chat know when the RFC is ready for comment

# Describe any ideas you've considered :bulb:
I thought Liam had started on a browser wallet document, but I can't find it now ...
Some other related github tickets: #[23](https://github.com/statechannels/project-management/issues/23), #[19](https://github.com/statechannels/project-management/issues/19). (If these tickets are no longer relevant, please close them)
Consider analyzing server wallet, and ensuring it's core functionality may be extended to a browser wallet (or defining how these core functionality may be extended)

# Project management
Before closing this card,
- [ ] I have created any required issues or epics
- [ ] I have updated the related notion or epic documentation

**Comment by kerzhner** [comment]
Closing in favor of https://github.com/statechannels/project-management/issues/76
