### ISSUE TITLE
Design document for Ledger Manager

### ISSUE THREAD

**Issue by wunnaii** [statechannels/statechannels#3355]
# Why: Problem description :grey_question:
The ledger manager work in #[3287](https://github.com/statechannels/statechannels/pull/3287) has a significant amount of code change. In order to review it efficiently, an accompanying design document would be helpful

# What: Describe what a solution should resolve :grey_exclamation:  
A document of sorts that
* summarizes the changes made
* identifies motivation behind any architectural decisions
* alternative approaches that were considered and reasoning for not implementing them

# Project management
Before closing this card,
- [x] I have created any required issues or epics [I don't believe any are required?]
- [x] I have updated the related notion or epic documentation [notion doc attached]

**Comment by tomclose** [comment]
https://www.notion.so/New-Ledger-Algorithm-8b7af9f5e43b40ccbb15d514e2f5fc32
