### ISSUE TITLE
implement createChannels

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3365]
# Why: Problem description :confused:
We want a `createChannels` method that is responsible for ensuring that a channel gets created.

The `createChannels` method should be added to a new `ChannelManager`. This method should use the `messageService` and `ensureObjectives` to make sure the objectives get created.

**Comment by lalexgap** [comment]
https://github.com/statechannels/statechannels/pull/3376#discussion_r595700510 has some relevent discussion.
