### ISSUE TITLE
Import xstate-wallet into monorepo

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#3395]
As part of reclaiming the xstate-wallet, we should:
1. Import the [`xstate-wallet` package](https://github.com/statechannels/legacy-packages/tree/master/packages/xstate-wallet) to the [monorepo](https://github.com/statechannels/statechannels). Make sure that git history is preserved.
2. Update `xstate-wallet` dependencies with the latest `@statechannels` packages. Reference [this branch](https://github.com/statechannels/statechannels/tree/xstate-wallet-reclaim) for how to do so. We might be able to cherry-pick commits from this branch.

**Comment by andrewgordstewart** [comment]
Can we simply revert the commit that deleted the package in the first place? Doing so, we would automatically restore the previous git history.

**Comment by kerzhner** [comment]
> Can we simply revert the commit that deleted the package in the first place? Doing so, we would automatically restore the previous git history.

That's probably worth trying. It looks like [this commit](https://github.com/statechannels/statechannels/commit/f5dd05fadf25e85acc0efa91cd4bc9ed0919437e) removes `xstate-wallet` (as well as other packages) from the repo.

**Comment by andrewgordstewart** [comment]
I think if you revert the commit, then modify that commit to only to restore the files that you want, you might get the desired outcome.

**Comment by kerzhner** [comment]
With `git revert` to undo package removal, all content of the `xstate-wallet` has the latest commit of `Revert "fix: remove stale packages`. This is probably not the git history that we want.
