### ISSUE TITLE
[nitro-protocol] Rename `channelStorageHashes`, considering new storage format.

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#34]
I am wondering if we still want to use 'hash' to refer to the data that is stored on chain? It is no longer the output of `keccak256`.

How about something like the following: the mapping is named `storageData`, and `_getHash` becomes `_encodeStorageDatum` etc?

_Originally posted by @geoknee in https://github.com/statechannels/nitro-protocol/pull/94_

**Comment by snario** [comment]
I think we need distinctions between 

- channel storage hash: the "encoding" / concatenation of channel storage
- channel storage: the triple
- channel data: the struct with the hash of the outcome and the appData
- channel state: a "full" struct with access to all data, no hashes

**Comment by snario** [comment]
Started a  branch for this
