### ISSUE TITLE
Clean up Engine Response Types

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#3461]
# Why: Problem description :confused:
The engine was originally designed to be externally accessible. However, now that we have a `wallet` that wraps the `engine` the current `EngineResponse` is a bit clunky.  We should update the `engine` so the return types are easy to work with in the `wallet`.
# What: Describe the solution you'd like :sparkles:  
- We should guarantee an objective is returned when a new objective should be created
- It should be easy to iterate through the results per objective

**Comment by andrewgordstewart** [comment]
Meta comment here: in spite of the clunky types you're observing, the usage of `EngineResponse` in our codebase seems like a really good pattern to me!

**Comment by andrewgordstewart** [comment]
Closed by #3528 (among others)
