### ISSUE TITLE
Flickering server-wallet-with-peers test

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3583]
[This run](https://app.circleci.com/pipelines/github/statechannels/statechannels/13103/workflows/522869dc-bce8-408a-8103-56a1f24b0b39/jobs/64964) was performed on `master`. It included a documentation change only, which should not affect the `with-peers` test.

**Comment by geoknee** [comment]
https://app.circleci.com/pipelines/github/statechannels/statechannels/13129/workflows/072b2d0f-d3cd-4b79-8741-fd24ca8e046a/jobs/65118

**Comment by lalexgap** [comment]
I am hoping that the eventless engine changes in 6368ddca63fa2f67ba9f90770902755ccf67ce59 have resolved this. I'll keep an eye on this and will close it in 2 weeks if we don't see any flickering.

**Comment by geoknee** [comment]
https://app.circleci.com/pipelines/github/statechannels/statechannels/13179/workflows/7f853d32-8e1f-4a4e-a05a-7639175929a1/jobs/65301

**Comment by geoknee** [comment]
Not on master, but another flicker https://app.circleci.com/pipelines/github/statechannels/statechannels/13457/workflows/02bb69aa-ede4-4bb5-b534-907a28b1ff86/jobs/65998

**Comment by geoknee** [comment]
https://app.circleci.com/pipelines/github/statechannels/statechannels/13511/workflows/22c29efe-0c6c-4b0a-a49c-c69cc421d688/jobs/66203
