### ISSUE TITLE
Allow load requests to depend on previous requests

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#3626]
Currently the load nodes will attempt to execute the load as quickly as possible. This makes co-operation between two nodes difficult.

Say we want this sequence:
- **A** create channel
- **A** update channel
- **B** update channel
 - **A** close channel
Right now **B**  could update the channel even before **A** creates or updates it.

To address this we should have a way of making B wait until the appropriate time.

## Proposed Solution
Each ServerOperationRequest would now have a step number. This is used to determine if an action is ready to be taken.

We could add an endpoint so nodes can communicate progress on a ServerOperationRequest. Whenever a `ServerWalletNode` handles a `ServerOperationRequest` it broadcasts that to all peers so a node knows when it can perform a ServerOperationRequest.

**Comment by andrewgordstewart** [comment]
Can the load specify timing at all? Can we simulate a scenario where a wallet receives a burst of new channel requests?

If so, that's one way to resolve the issue, by choosing the timestamp to execute "**B** update channel" after "**A** create channel".

**Comment by lalexgap** [comment]
This functionality has been removed after the demo.
