### ISSUE TITLE
check assets match in target and guarantor during claim

### ISSUE THREAD

**Issue by geoknee** [statechannels/statechannels#3672]
(on the pushOutcome-trunk branch #3624).

We should write a test that fails, first.

**Comment by geoknee** [comment]
We also need to consider whether this fix needs to be applied to the exit-format repo, too!

**Comment by NiloCK** [comment]
A little more context. Currently, the external `MultiAssetHolder.claim(...)` [function](https://github.com/statechannels/statechannels/blob/ea8f896b24658212f680e3a1664729065e556057/packages/nitro-protocol/contracts/MultiAssetHolder.sol#L134) receives an `assetIndex` uint from the caller, which it uses to:

- [pull](https://github.com/statechannels/statechannels/blob/ea8f896b24658212f680e3a1664729065e556057/packages/nitro-protocol/contracts/MultiAssetHolder.sol#L168) an individual `AssetOutcome`, the guarantee, out of the guarantor channel's outcome and decode it
- [determine](https://github.com/statechannels/statechannels/blob/ea8f896b24658212f680e3a1664729065e556057/packages/nitro-protocol/contracts/MultiAssetHolder.sol#L176) the asset in question
- [pull](https://github.com/statechannels/statechannels/blob/ea8f896b24658212f680e3a1664729065e556057/packages/nitro-protocol/contracts/MultiAssetHolder.sol#L195) an individual `AssetOutcome` out of the target channel's outcome, decode it, and then decode its list of `AllocationItems`

The determined asset, guarantee, and target Allocation are passed to the internal `_claim` function.

Potential issue is that there are no checks in place to confirm that the target channel's `outcome[assetIndex]` refers to the same determined asset as the guarantee, which opens up a potential attack vector where, say, a guarantee of USDT tokens is used to update the ETH allocation on a target channel.
