### ISSUE TITLE
Broken dependency in npm package

### ISSUE THREAD

**Issue by DromedaryCamel** [statechannels/statechannels#3717]
**Describe the bug**
I have installed the most recent npm packages but I can't seem to get rid of this dependency issue. It was working before I updated from the previous version.

**Logs**
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/es-app/node_modules/@statechannels/server-wallet/lib/src/chain-service/chain-service.js',
    '/es-app/node_modules/@statechannels/server-wallet/lib/src/chain-service/index.js',
    '/es-app/node_modules/@statechannels/server-wallet/lib/src/wallet/wallet.js',
    '/es-app/node_modules/@statechannels/server-wallet/lib/src/wallet/index.js',
    '/es-app/node_modules/@statechannels/server-wallet/lib/src/index.js',
    '/es-app/dist/src/engine-helpers.js',
    '/es-app/dist/src/index.js'
  ]

**Screenshots**
![depError](https://user-images.githubusercontent.com/79185811/128095560-cd5cc196-b064-441e-a73a-0b05b66f2d01.png)

**Comment by geoknee** [comment]
@DromedaryCamel  Thanks for raising this! We are working on a fix and should have that published shortly. 

Meanwhile, would you let us know a little more about your interest in our project? We may be able to provide you some more support. We can add you to our slack, for example.

**Comment by geoknee** [comment]
@DromedaryCamel I've published a new version (1.25.1) of server-wallet. Please let me know if that solves this problem for you!

**Comment by DromedaryCamel** [comment]
> @DromedaryCamel Thanks for raising this! We are working on a fix and should have that published shortly.
> 
> Meanwhile, would you let us know a little more about your interest in our project? We may be able to provide you some more support. We can add you to our slack, for example.

@geoknee Thank you very much for the quick resolution. I am creating a game, somewhat similar to chess but with many different creatures/pieces. Users bring a preconstructed team and are able to play off-chain. Winner takes a piece from the opponent. Some of the ideas are a bit out of scope for your project, but I am mostly doing it for fun and to see if I can make it work. I currently have the full game running on a local chain using this project, except for original channel funding, which may prove to be a big hurdle. Thanks for your time.

**Comment by DromedaryCamel** [comment]
> @DromedaryCamel I've published a new version (1.25.1) of server-wallet. Please let me know if that solves this problem for you!

The issue has been solved. Thank you!
