### ISSUE TITLE
Improve legibility of `claim`, `transfer`

### ISSUE THREAD

**Issue by NiloCK** [statechannels/statechannels#3728]
# Why: Problem description :confused:
`transfer` and (especially) `claim` are complicated operations. This is unavoidable is some respects ([no-silver-bullet](http://worrydream.com/refs/Brooks-NoSilverBullet.pdf)) as the protocol itself has essential complexity which must be reflected in the implementation.

Given their central importance in the protocol, we should *make every effort* to maximize their legibility.

# What :sparkles:  

This issue thread is a placeholder for thoughts on potentially useful refactors.

**Comment by NiloCK** [comment]
https://github.com/statechannels/statechannels/pull/3714#discussion_r683572321

**Comment by geoknee** [comment]
via #3758
