### ISSUE TITLE
[nitro-protocol] Test Transaction Generators

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#61]
Currently we expose various transaction generators to create transactions for various `ForceMove` functions.

Right now there are no test that makes sure the transactions that we generate actually run correctly against the contracts. 

We should add some basic tests that call the transaction generator and then send the transaction to ganache to ensure they work as expected.

The existing contract tests in  'packages/nitro-protocol/test/contracts` show how we can write these new tests to interact with a ganache instance.

**Comment by geoknee** [comment]
- [x] forceMove #888 
- [ ]  other transactions
