### ISSUE TITLE
Remove usage of npx in package.json scripts

### ISSUE THREAD

**Issue by snario** [statechannels/statechannels#617]
I'm not quite sure why we use `npx` over `yarn run`. I think the intent of `npx` is for temporary scripts or packages which have a `bin` file with some directly-runnable scripts in them. In almost all cases that we use `npx` though, `yarn run` works exactly the same way. In one case, with `ts-node`, I observed that `npx ts-node ...` threw an error but `yarn run ts-node ...` threw an error with the full stack trace, which is at least one benefit.

**Comment by tomclose** [comment]
I'm happy for this to be changed. I've recently added more `npx`s in [this PR](https://github.com/statechannels/monorepo/pull/631), but that's only because I was following the pattern that was already there.

**Comment by snario** [comment]
I also noticed we can just refer to the package directly. For example, changing:

```diff
{
  "scripts: {
-    "test": "npx jest"
+    "test": "jest"
  }
}
```

**Comment by andrewgordstewart** [comment]
> I also noticed we can just refer to the package directly. For example, changing:
> 
> ```diff
> {
>   "scripts: {
> -    "test": "npx jest"
> +    "test": "jest"
>   }
> }
> ```

How does yarn know not to call a binary called `jest` that's defined in your `$PATH`? The documentation doesn't seem to cover this.
