### ISSUE TITLE
Add solution to detect TypeScript build issues in test files before tests start runninga

### ISSUE THREAD

**Issue by snario** [statechannels/statechannels#618]
I just wasted 10 minutes waiting for this CI to pass: https://circleci.com/gh/statechannels/monorepo/5201?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

And it turns out there was a TypeScript build error in one of the test files.

`hub/tsconfig.json` does not build `test/**/*` files so it makes sense it had to wait for `jest` to attempt to build them before running them.

However we _do have_ a `build` step with `yarn build`, but the annoying part is we don't want those test files in our `dist` files for the hub. 

So is there a solution?

**Comment by snario** [comment]
Actually I might be crazy / very tired as that CI job failed on `yarn build`... but I thought it had not when I ran `yarn build` locally. A bit confused.

**Comment by kerzhner** [comment]
To clarify, what is the desired outcome of resolving this issue? Is it to detect typescript issues during CI build step? Or is it to learn about typescript issues as quickly as possible? If it is the latter, perhaps a git pre-push hook might be handy.

**Comment by snario** [comment]
It is to learn about typescript issues as quickly as possible.
