### ISSUE TITLE
Stronger typing for the ChannelProvider

### ISSUE THREAD

**Issue by tomclose** [statechannels/statechannels#691]
The [channel provider interface](https://github.com/statechannels/monorepo/blob/master/packages/channel-provider/src/types.ts#L49-L56) isn't very sophisticated at the moment; for example, it doesn't capture the relationships between request names, request formats, and responses that exist in the api. It would be nice if the following code gave a type error:
```ts
provider.send('CreateChannel', {channelId: '0x123'});  // passing the params for 'UpdateChannel'
```

I made a start at attempt at this on https://github.com/statechannels/monorepo/pull/671/files, which didn't work (though some of the code might still be useful). I think I now understand what will work, by looking at how [event emitter do it](https://github.com/primus/eventemitter3/blob/master/index.d.ts). It turns out the trick is to use interfaces with method names as keys. You'll need something like the following:
```ts
interface Notifications {
  ChannelProposed: JsonRPCNotification<'ChannelProposed', ChannelResult>;
  ChannelUpdated: JsonRPCNotification<'ChannelUpdated', ChannelResult>;
  ChannelClosed: JsonRPCNotification<'ChannelClosed', ChannelResult>;
  MessageQueued: JsonRPCNotification<'MessageQueued', Message>;
}

type NotificationName = keyof Notifications;

function on<Name extends NotificationName>(name: Name, callback: (args: Notifications[Name].params) => void) {... };

on('ChannelClosed', (x: string) => console.log(x)) // type error, as the callback is of the wrong type
```
The aim of this piece of work is to upgrade the `IProvider` so that:
1. Binding a callback of the wrong type in `on` gives an error
2. Providing args of the wrong type in `send` gives an error
3. Calling code can infer the return type of `send` (e.g. it should know that if you `await send('PushMessage', ...)` the result will be of type `{ success: boolean }`.

**Comment by snario** [comment]
I think this has been fixed already. We have typing for the requests and responses now.

**Comment by andrewgordstewart** [comment]
> 3. Calling code can infer the return type of `send` (e.g. it should know that if you `await send('PushMessage', ...)` the result will be of type `{ success: boolean }`.

I don't think we have this level of typing. Do we care about it?

**Comment by snario** [comment]
I spent some time making this work before and it led to this

https://github.com/statechannels/monorepo/blob/893845fd0dc2fb398ed298055aa53fb8a1505a74/packages/channel-provider/src/types.ts#L144-L145

I think it's still working?

**Comment by andrewgordstewart** [comment]
Right now, it seems to return `Promise<any>`

<img width="719" alt="Screen Shot 2020-05-21 at 11 22 48 AM" src="https://user-images.githubusercontent.com/8432675/82592255-7b37c780-9b55-11ea-80c2-c012507908d7.png">


I think it's pretty close to being able to return a union type (the response type or one of the error types), but it doesn't quite do that.

**Comment by snario** [comment]
Hm maybe it broken somehow. I'll look into it.
