### ISSUE TITLE
Create deployment script for pushing contracts to Ropsten

### ISSUE THREAD

**Issue by snario** [statechannels/statechannels#927]
Right now I am manually doing this with a one-off script that uses `ethers` and a hard-coded Infura provider with my personal API key and MetaMask account. We ought to have a slightly more robust solution so deploying is easy and anyone can do it.

Bonus:
- Auto-verify source code on Etherscan after

**Comment by snario** [comment]
cc @Alonski

**Comment by Alonski** [comment]
I thought I created an issue for this
