### ISSUE TITLE
Improve maintainability of machine configurations

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#959]
_Originally posted by @tomclose in https://github.com/statechannels/monorepo/pull/936_

> This isn't really a comment about this specific PR, but more about x-state, or at least the way we're using it. This line makes me feel really uneasy. As someone who's reading the code, essentially there are some magic strings being passed to a function. There doesn't seem to be an easy way for me to trace these back to where they're defined, or inspect their types, or understand what's going to be passed to them. I get that connecting services to machine config via strings allows for the implementation to be decoupled, but it seems like we have so much decoupling that it becomes harder to figure out what the actual code does.
> 
> It would be good to discuss this further, and figure out if there are patterns we can use to make our x-state code easier to read and understand.

**Comment by snario** [comment]
Want to keep this issue alive or opt for more specific ones? We seem to be having this discussion now with @tomclose's recent work on a separate application workflow for directly funded channels.
